
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,r,ba=new Promise((a,b)=>{aa=a;r=b}),ca="object"==typeof window,t="function"==typeof importScripts,u="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(u){const {createRequire:a}=await import("module");let b=import.meta.url;b.startsWith("data:")&&(b="/");var require=a(b)}var da=Object.assign({},f),v=(a,b)=>{throw b;},w="",y,z;
if(u){var fs=require("fs"),A=require("path");import.meta.url.startsWith("data:")||(w=A.dirname(require("url").fileURLToPath(import.meta.url))+"/");z=a=>{a=B(a)?new URL(a):A.normalize(a);return fs.readFileSync(a)};y=a=>{a=B(a)?new URL(a):A.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};process.argv.slice(2);v=(a,b)=>{process.exitCode=a;throw b;}}else if(ca||t)t?w=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(w=document.currentScript.src),_scriptName&&(w=_scriptName),w.startsWith("blob:")?w="":w=w.substr(0,w.replace(/[?#].*/,"").lastIndexOf("/")+1),t&&(z=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),y=a=>B(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));f.print||console.log.bind(console);var C=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;var D=f.wasmBinary,E,F=!1,G,H,I,J,K,L,M,ea,fa;function ha(){var a=E.buffer;f.HEAP8=H=new Int8Array(a);f.HEAP16=J=new Int16Array(a);f.HEAPU8=I=new Uint8Array(a);f.HEAPU16=K=new Uint16Array(a);f.HEAP32=L=new Int32Array(a);f.HEAPU32=M=new Uint32Array(a);f.HEAPF32=ea=new Float32Array(a);f.HEAPF64=fa=new Float64Array(a)}
var ja=[],ka=[],la=[];function ma(){var a=f.preRun.shift();ja.unshift(a)}var N=0,O=null,P=null;function na(a){f.onAbort?.(a);a="Aborted("+a+")";C(a);F=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");r(a);throw a;}var oa=a=>a.startsWith("data:application/octet-stream;base64,"),B=a=>a.startsWith("file://"),Q;function pa(a){if(a==Q&&D)return new Uint8Array(D);if(z)return z(a);throw"both async and sync fetching of the wasm failed";}
function qa(a){return D?Promise.resolve().then(()=>pa(a)):y(a).then(b=>new Uint8Array(b),()=>pa(a))}function ra(a,b,c){return qa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{C(`failed to asynchronously prepare wasm: ${d}`);na(d)})}
function sa(a,b){var c=Q;return D||"function"!=typeof WebAssembly.instantiateStreaming||oa(c)||B(c)||u||"function"!=typeof fetch?ra(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){C(`wasm streaming compile failed: ${e}`);C("falling back to ArrayBuffer instantiation");return ra(c,a,b)}))}function ta(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var ua=a=>{for(;0<a.length;)a.shift()(f)},va=f.noExitRuntime||!0,wa,R=a=>{for(var b="";I[a];)b+=wa[I[a++]];return b},xa={},ya={},za={},S;function Aa(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(ya.hasOwnProperty(a)){if(c.A)return;throw new S(`Cannot register type '${d}' twice`);}ya[a]=b;delete za[a];xa.hasOwnProperty(a)&&(b=xa[a],delete xa[a],b.forEach(e=>e()))}function T(a,b,c={}){return Aa(a,b,c)}
var Ba=[],U=[],Da=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ba.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function Ea(a){return this.fromWireType(M[a>>2])}
for(var Fa={name:"emscripten::val",fromWireType:a=>{if(!a)throw new S("Cannot use deleted val. handle = "+a);var b=U[a];9<a&&0===--U[a+1]&&(U[a]=void 0,Ba.push(a));return b},toWireType:(a,b)=>Da(b),u:8,readValueFromPointer:Ea,v:null},Ga=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ea[c>>2])};case 8:return function(c){return this.fromWireType(fa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ha=(a,b,c)=>{switch(b){case 1:return c?d=>H[d]:d=>I[d];
case 2:return c?d=>J[d>>1]:d=>K[d>>1];case 4:return c?d=>L[d>>2]:d=>M[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ia="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Ka=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&K[c];)++c;c<<=1;if(32<c-a&&Ja)return Ja.decode(I.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=J[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},La=(a,b,c)=>{c??=2147483647;
if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)J[b>>1]=a.charCodeAt(e),b+=2;J[b>>1]=0;return b-d},Ma=a=>2*a.length,Na=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=L[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Oa=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var g=a.charCodeAt(++e);h=65536+((h&1023)<<
10)|g&1023}L[b>>2]=h;b+=4;if(b+4>c)break}L[b>>2]=0;return b-d},Pa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},V={},Qa=0,Ra=a=>{G=a;va||0<Qa||(f.onExit?.(a),F=!0);v(a,new ta(a))},Sa=a=>{if(!F)try{if(a(),!(va||0<Qa))try{G=a=G,Ra(a)}catch(b){b instanceof ta||"unwind"==b||v(1,b)}}catch(b){b instanceof ta||"unwind"==b||v(1,b)}},Ta=Array(256),W=0;256>W;++W)Ta[W]=String.fromCharCode(W);wa=Ta;
S=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};U.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>U.length/2-5-Ba.length;
var Wa={i:()=>{na("")},j:()=>{},g:(a,b,c,d)=>{b=R(b);T(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,h){return h?c:d},u:8,readValueFromPointer:function(e){return this.fromWireType(I[e])},v:null})},f:a=>T(a,Fa),d:(a,b,c)=>{b=R(b);T(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,u:8,readValueFromPointer:Ga(b,c),v:null})},b:(a,b,c,d,e)=>{b=R(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var h=32-8*c;e=k=>k<<h>>>h}var g=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,
m){return m};T(a,{name:b,fromWireType:e,toWireType:g,u:8,readValueFromPointer:Ha(b,c,0!==d),v:null})},a:(a,b,c)=>{function d(h){return new e(H.buffer,M[h+4>>2],M[h>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);T(a,{name:c,fromWireType:d,u:8,readValueFromPointer:d},{A:!0})},e:(a,b)=>{b=R(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=M[d>>2],h=d+4;if(c)for(var g=h,k=0;k<=e;++k){var m=h+k;if(k==e||0==I[m]){if(g){var n=
g;var l=I,q=n+(m-g);for(g=n;l[g]&&!(g>=q);)++g;if(16<g-n&&l.buffer&&Ia)n=Ia.decode(l.subarray(n,g));else{for(q="";n<g;){var p=l[n++];if(p&128){var ia=l[n++]&63;if(192==(p&224))q+=String.fromCharCode((p&31)<<6|ia);else{var Ca=l[n++]&63;p=224==(p&240)?(p&15)<<12|ia<<6|Ca:(p&7)<<18|ia<<12|Ca<<6|l[n++]&63;65536>p?q+=String.fromCharCode(p):(p-=65536,q+=String.fromCharCode(55296|p>>10,56320|p&1023))}}else q+=String.fromCharCode(p)}n=q}}else n="";if(void 0===x)var x=n;else x+=String.fromCharCode(0),x+=n;
g=m+1}}else{x=Array(e);for(k=0;k<e;++k)x[k]=String.fromCharCode(I[h+k]);x=x.join("")}X(d);return x},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,g="string"==typeof e;if(!(g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new S("Cannot pass non-string to std::string");var k;if(c&&g)for(h=k=0;h<e.length;++h){var m=e.charCodeAt(h);127>=m?k++:2047>=m?k+=2:55296<=m&&57343>=m?(k+=4,++h):k+=3}else k=e.length;h=k;k=Ua(4+h+1);m=k+4;
M[k>>2]=h;if(c&&g){if(g=m,m=h+1,h=I,0<m){m=g+m-1;for(var n=0;n<e.length;++n){var l=e.charCodeAt(n);if(55296<=l&&57343>=l){var q=e.charCodeAt(++n);l=65536+((l&1023)<<10)|q&1023}if(127>=l){if(g>=m)break;h[g++]=l}else{if(2047>=l){if(g+1>=m)break;h[g++]=192|l>>6}else{if(65535>=l){if(g+2>=m)break;h[g++]=224|l>>12}else{if(g+3>=m)break;h[g++]=240|l>>18;h[g++]=128|l>>12&63}h[g++]=128|l>>6&63}h[g++]=128|l&63}}h[g]=0}}else if(g)for(g=0;g<h;++g){n=e.charCodeAt(g);if(255<n)throw X(m),new S("String has UTF-16 code units that do not fit in 8 bits");
I[m+g]=n}else for(g=0;g<h;++g)I[m+g]=e[g];null!==d&&d.push(X,k);return k},u:8,readValueFromPointer:Ea,v(d){X(d)}})},c:(a,b,c)=>{c=R(c);if(2===b){var d=Ka;var e=La;var h=Ma;var g=k=>K[k>>1]}else 4===b&&(d=Na,e=Oa,h=Pa,g=k=>M[k>>2]);T(a,{name:c,fromWireType:k=>{for(var m=M[k>>2],n,l=k+4,q=0;q<=m;++q){var p=k+4+q*b;if(q==m||0==g(p))l=d(l,p-l),void 0===n?n=l:(n+=String.fromCharCode(0),n+=l),l=p+b}X(k);return n},toWireType:(k,m)=>{if("string"!=typeof m)throw new S(`Cannot pass non-string to C++ string type ${c}`);
var n=h(m),l=Ua(4+n+b);M[l>>2]=n/b;e(m,l+4,n+b);null!==k&&k.push(X,l);return l},u:8,readValueFromPointer:Ea,v(k){X(k)}})},h:(a,b)=>{b=R(b);T(a,{B:!0,name:b,u:0,fromWireType:()=>{},toWireType:()=>{}})},l:()=>{va=!1;Qa=0},m:(a,b)=>{V[a]&&(clearTimeout(V[a].id),delete V[a]);if(!b)return 0;var c=setTimeout(()=>{delete V[a];Sa(()=>Va(a,performance.now()))},b);V[a]={id:c,C:b};return 0},n:a=>{var b=I.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-E.buffer.byteLength+65535)/65536;try{E.grow(d);ha();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},k:Ra},Y=function(){function a(c){Y=c.exports;E=Y.o;ha();ka.unshift(Y.p);N--;f.monitorRunDependencies?.(N);0==N&&(null!==O&&(clearInterval(O),O=null),P&&(c=P,P=null,c()));return Y}var b={a:Wa};N++;f.monitorRunDependencies?.(N);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){C(`Module.instantiateWasm callback failed with error: ${c}`),
r(c)}Q??=f.locateFile?oa("countup.wasm")?"countup.wasm":f.locateFile?f.locateFile("countup.wasm",w):w+"countup.wasm":(new URL("countup.wasm",import.meta.url)).href;sa(b,function(c){a(c.instance)}).catch(r);return{}}();f._countColors=(a,b)=>(f._countColors=Y.q)(a,b);var Va=(a,b)=>(Va=Y.r)(a,b),Ua=f._malloc=a=>(Ua=f._malloc=Y.s)(a),X=f._free=a=>(X=f._free=Y.t)(a),Z;P=function Xa(){Z||Ya();Z||(P=Xa)};
function Ya(){function a(){if(!Z&&(Z=!0,f.calledRun=!0,!F)){ua(ka);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();la.unshift(b)}ua(la)}}if(!(0<N)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ma();ua(ja);0<N||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Ya();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default Module;
