
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,p,ba=new Promise((a,b)=>{aa=a;p=b}),ca="object"==typeof window,q="undefined"!=typeof WorkerGlobalScope,da=Object.assign({},f),r="",ea,t;
if(ca||q)q?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),_scriptName&&(r=_scriptName),r.startsWith("blob:")?r="":r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1),q&&(t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var u=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;var v=f.wasmBinary,w,x=!1,y,z,A,B,C,D,E,fa,ha;function ia(){var a=w.buffer;f.HEAP8=z=new Int8Array(a);f.HEAP16=B=new Int16Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=C=new Uint16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU32=E=new Uint32Array(a);f.HEAPF32=fa=new Float32Array(a);f.HEAPF64=ha=new Float64Array(a)}var ja=[],ka=[],la=[];function ma(){var a=f.preRun.shift();ja.unshift(a)}var F=0,G=null;
function na(a){f.onAbort?.(a);a="Aborted("+a+")";u(a);x=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");p(a);throw a;}var oa=a=>a.startsWith("data:application/octet-stream;base64,"),H;async function pa(a){if(!v)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==H&&v)a=new Uint8Array(v);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}
async function qa(a,b){try{var d=await pa(a);return await WebAssembly.instantiate(d,b)}catch(c){u(`failed to asynchronously prepare wasm: ${c}`),na(c)}}async function ra(a){var b=H;if(!v&&"function"==typeof WebAssembly.instantiateStreaming&&!oa(b)&&"function"==typeof fetch)try{var d=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(c){u(`wasm streaming compile failed: ${c}`),u("falling back to ArrayBuffer instantiation")}return qa(b,a)}
class sa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var I=a=>{for(;0<a.length;)a.shift()(f)},J=f.noExitRuntime||!0,ta,K=a=>{for(var b="";A[a];)b+=ta[A[a++]];return b},M={},ua={},va={},N;
function wa(a,b,d={}){var c=b.name;if(!a)throw new N(`type "${c}" must have a positive integer typeid pointer`);if(ua.hasOwnProperty(a)){if(d.A)return;throw new N(`Cannot register type '${c}' twice`);}ua[a]=b;delete va[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(e=>e()))}function O(a,b,d={}){return wa(a,b,d)}var P=[],Q=[],xa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=P.pop()||Q.length;Q[b]=a;Q[b+1]=1;return b}};
function R(a){return this.fromWireType(E[a>>2])}
for(var ya={name:"emscripten::val",fromWireType:a=>{if(!a)throw new N("Cannot use deleted val. handle = "+a);var b=Q[a];9<a&&0===--Q[a+1]&&(Q[a]=void 0,P.push(a));return b},toWireType:(a,b)=>xa(b),u:8,readValueFromPointer:R,v:null},za=(a,b)=>{switch(b){case 4:return function(d){return this.fromWireType(fa[d>>2])};case 8:return function(d){return this.fromWireType(ha[d>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Aa=(a,b,d)=>{switch(b){case 1:return d?c=>z[c]:c=>A[c];case 2:return d?
c=>B[c>>1]:c=>C[c>>1];case 4:return d?c=>D[c>>2]:c=>E[c>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ba="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Ca=(a=0,b=NaN)=>{var d=A,c=a+b;for(b=a;d[b]&&!(b>=c);)++b;if(16<b-a&&d.buffer&&Ba)return Ba.decode(d.subarray(a,b));for(c="";a<b;){var e=d[a++];if(e&128){var g=d[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var k=d[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|d[a++]&63;65536>e?
c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Da="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Ea=(a,b)=>{var d=a>>1;for(var c=d+b/2;!(d>=c)&&C[d];)++d;d<<=1;if(32<d-a&&Da)return Da.decode(A.subarray(a,d));d="";for(c=0;!(c>=b/2);++c){var e=B[a+2*c>>1];if(0==e)break;d+=String.fromCharCode(e)}return d},Fa=(a,b,d)=>{d??=2147483647;if(2>d)return 0;d-=2;var c=b;d=d<2*a.length?d/2:a.length;for(var e=0;e<
d;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-c},Ga=a=>2*a.length,Ha=(a,b)=>{for(var d=0,c="";!(d>=b/4);){var e=D[a+4*d>>2];if(0==e)break;++d;65536<=e?(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023)):c+=String.fromCharCode(e)}return c},Ia=(a,b,d)=>{d??=2147483647;if(4>d)return 0;var c=b;d=c+d-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var k=a.charCodeAt(++e);g=65536+((g&1023)<<10)|k&1023}D[b>>2]=g;b+=4;if(b+4>d)break}D[b>>2]=0;return b-c},Ja=a=>{for(var b=
0,d=0;d<a.length;++d){var c=a.charCodeAt(d);55296<=c&&57343>=c&&++d;b+=4}return b},S=0,T={},Ka=a=>{if(!(a instanceof sa||"unwind"==a))throw a;},La=a=>{y=a;J||0<S||(f.onExit?.(a),x=!0);throw new sa(a);},Ma=a=>{if(!x)try{if(a(),!(J||0<S))try{y=a=y,La(a)}catch(b){Ka(b)}}catch(b){Ka(b)}},Na=Array(256),U=0;256>U;++U)Na[U]=String.fromCharCode(U);ta=Na;N=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Q.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>Q.length/2-5-P.length;
var Pa={i:()=>na(""),j:()=>{},g:(a,b,d,c)=>{b=K(b);O(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?d:c},u:8,readValueFromPointer:function(e){return this.fromWireType(A[e])},v:null})},e:a=>O(a,ya),d:(a,b,d)=>{b=K(b);O(a,{name:b,fromWireType:c=>c,toWireType:(c,e)=>e,u:8,readValueFromPointer:za(b,d),v:null})},b:(a,b,d,c,e)=>{b=K(b);-1===e&&(e=4294967295);e=h=>h;if(0===c){var g=32-8*d;e=h=>h<<g>>>g}var k=b.includes("unsigned")?function(h,m){return m>>>0}:function(h,m){return m};
O(a,{name:b,fromWireType:e,toWireType:k,u:8,readValueFromPointer:Aa(b,d,0!==c),v:null})},a:(a,b,d)=>{function c(g){return new e(z.buffer,E[g+4>>2],E[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];d=K(d);O(a,{name:d,fromWireType:c,u:8,readValueFromPointer:c},{A:!0})},f:(a,b)=>{b=K(b);O(a,{name:b,fromWireType:function(d){for(var c=E[d>>2],e=d+4,g,k=e,h=0;h<=c;++h){var m=e+h;if(h==c||0==A[m])k=k?Ca(k,m-k):"",void 0===g?g=k:(g+=String.fromCharCode(0),
g+=k),k=m+1}V(d);return g},toWireType:function(d,c){c instanceof ArrayBuffer&&(c=new Uint8Array(c));var e,g="string"==typeof c;if(!(g||c instanceof Uint8Array||c instanceof Uint8ClampedArray||c instanceof Int8Array))throw new N("Cannot pass non-string to std::string");var k;if(g)for(e=k=0;e<c.length;++e){var h=c.charCodeAt(e);127>=h?k++:2047>=h?k+=2:55296<=h&&57343>=h?(k+=4,++e):k+=3}else k=c.length;e=k;k=W(4+e+1);h=k+4;E[k>>2]=e;if(g){if(g=h,h=e+1,e=A,0<h){h=g+h-1;for(var m=0;m<c.length;++m){var l=
c.charCodeAt(m);if(55296<=l&&57343>=l){var n=c.charCodeAt(++m);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(g>=h)break;e[g++]=l}else{if(2047>=l){if(g+1>=h)break;e[g++]=192|l>>6}else{if(65535>=l){if(g+2>=h)break;e[g++]=224|l>>12}else{if(g+3>=h)break;e[g++]=240|l>>18;e[g++]=128|l>>12&63}e[g++]=128|l>>6&63}e[g++]=128|l&63}}e[g]=0}}else if(g)for(g=0;g<e;++g){m=c.charCodeAt(g);if(255<m)throw V(h),new N("String has UTF-16 code units that do not fit in 8 bits");A[h+g]=m}else for(g=0;g<e;++g)A[h+g]=c[g];null!==
d&&d.push(V,k);return k},u:8,readValueFromPointer:R,v(d){V(d)}})},c:(a,b,d)=>{d=K(d);if(2===b){var c=Ea;var e=Fa;var g=Ga;var k=h=>C[h>>1]}else 4===b&&(c=Ha,e=Ia,g=Ja,k=h=>E[h>>2]);O(a,{name:d,fromWireType:h=>{for(var m=E[h>>2],l,n=h+4,L=0;L<=m;++L){var Z=h+4+L*b;if(L==m||0==k(Z))n=c(n,Z-n),void 0===l?l=n:(l+=String.fromCharCode(0),l+=n),n=Z+b}V(h);return l},toWireType:(h,m)=>{if("string"!=typeof m)throw new N(`Cannot pass non-string to C++ string type ${d}`);var l=g(m),n=W(4+l+b);E[n>>2]=l/b;e(m,
n+4,l+b);null!==h&&h.push(V,n);return n},u:8,readValueFromPointer:R,v(h){V(h)}})},h:(a,b)=>{b=K(b);O(a,{B:!0,name:b,u:0,fromWireType:()=>{},toWireType:()=>{}})},l:()=>{J=!1;S=0},m:(a,b)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!b)return 0;var d=setTimeout(()=>{delete T[a];Ma(()=>Oa(a,performance.now()))},b);T[a]={id:d,C:b};return 0},n:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var c=b*(1+.2/d);c=Math.min(c,a+100663296);a:{c=(Math.min(2147483648,65536*Math.ceil(Math.max(a,
c)/65536))-w.buffer.byteLength+65535)/65536|0;try{w.grow(c);ia();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},k:La},X;
(async function(){function a(c){X=c.exports;w=X.o;ia();ka.unshift(X.p);F--;f.monitorRunDependencies?.(F);0==F&&G&&(c=G,G=null,c());return X}F++;f.monitorRunDependencies?.(F);var b={a:Pa};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){u(`Module.instantiateWasm callback failed with error: ${c}`),p(c)}H??=f.locateFile?oa("countup.wasm")?"countup.wasm":f.locateFile?f.locateFile("countup.wasm",r):r+"countup.wasm":(new URL("countup.wasm",import.meta.url)).href;try{var d=await ra(b);
a(d.instance);return d}catch(c){p(c)}})();f._countColors=(a,b)=>(f._countColors=X.q)(a,b);var Oa=(a,b)=>(Oa=X.r)(a,b),W=f._malloc=a=>(W=f._malloc=X.s)(a),V=f._free=a=>(V=f._free=X.t)(a),Y;G=function Qa(){Y||Ra();Y||(G=Qa)};
function Ra(){function a(){if(!Y&&(Y=!0,f.calledRun=!0,!x)){I(ka);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();la.unshift(b)}I(la)}}if(!(0<F)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ma();I(ja);0<F||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Ra();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default Module;
