
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,r,ba=new Promise((a,b)=>{aa=a;r=b}),ca="object"==typeof window,da="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(ea){const {createRequire:a}=await import("module");let b=import.meta.url;b.startsWith("data:")&&(b="/");var require=a(b)}var fa=Object.assign({},f),t=(a,b)=>{throw b;},u="",ha,x;
if(ea){var fs=require("fs"),ia=require("path");import.meta.url.startsWith("data:")||(u=ia.dirname(require("url").fileURLToPath(import.meta.url))+"/");x=a=>{a=y(a)?new URL(a):ia.normalize(a);return fs.readFileSync(a)};ha=a=>{a=y(a)?new URL(a):ia.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};process.argv.slice(2);t=(a,b)=>{process.exitCode=a;throw b;}}else if(ca||da)da?u=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(u=document.currentScript.src),_scriptName&&(u=_scriptName),u.startsWith("blob:")?u="":u=u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1),da&&(x=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=a=>y(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));f.print||console.log.bind(console);var B=f.printErr||console.error.bind(console);Object.assign(f,fa);fa=null;var C=f.wasmBinary,D,E=!1,ja,ka,G,H,I,J,K,la,ma;function na(){var a=D.buffer;f.HEAP8=ka=new Int8Array(a);f.HEAP16=H=new Int16Array(a);f.HEAPU8=G=new Uint8Array(a);f.HEAPU16=I=new Uint16Array(a);f.HEAP32=J=new Int32Array(a);f.HEAPU32=K=new Uint32Array(a);f.HEAPF32=la=new Float32Array(a);f.HEAPF64=ma=new Float64Array(a)}
var oa=[],pa=[],qa=[];function ra(){var a=f.preRun.shift();oa.unshift(a)}var L=0,sa=null,M=null;function ta(a){f.onAbort?.(a);a="Aborted("+a+")";B(a);E=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");r(a);throw a;}var ua=a=>a.startsWith("data:application/octet-stream;base64,"),y=a=>a.startsWith("file://"),va;function wa(a){if(a==va&&C)return new Uint8Array(C);if(x)return x(a);throw"both async and sync fetching of the wasm failed";}
function xa(a){return C?Promise.resolve().then(()=>wa(a)):ha(a).then(b=>new Uint8Array(b),()=>wa(a))}function za(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{B(`failed to asynchronously prepare wasm: ${d}`);ta(d)})}
function Aa(a,b){var c=va;return C||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||y(c)||ea||"function"!=typeof fetch?za(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){B(`wasm streaming compile failed: ${e}`);B("falling back to ArrayBuffer instantiation");return za(c,a,b)}))}function Ba(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ca=a=>{for(;0<a.length;)a.shift()(f)},Da=f.noExitRuntime||!0;class Ea{constructor(a){this.M=a-24}}
var Fa=0,Ga=0,Ha,N=a=>{for(var b="";G[a];)b+=Ha[G[a++]];return b},O={},P={},R={},S,Ia=a=>{throw new S(a);},Ja,Ka=(a,b)=>{function c(g){g=b(g);if(g.length!==d.length)throw new Ja("Mismatched type converter count");for(var m=0;m<d.length;++m)T(d[m],g[m])}var d=[];d.forEach(g=>R[g]=a);var e=Array(a.length),k=[],l=0;a.forEach((g,m)=>{P.hasOwnProperty(g)?e[m]=P[g]:(k.push(g),O.hasOwnProperty(g)||(O[g]=[]),O[g].push(()=>{e[m]=P[g];++l;l===k.length&&c(e)}))});0===k.length&&c(e)};
function La(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(P.hasOwnProperty(a)){if(c.O)return;throw new S(`Cannot register type '${d}' twice`);}P[a]=b;delete R[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(e=>e()))}function T(a,b,c={}){return La(a,b,c)}
var Ma=[],U=[],Na=a=>{9<a&&0===--U[a+1]&&(U[a]=void 0,Ma.push(a))},V=a=>{if(!a)throw new S("Cannot use deleted val. handle = "+a);return U[a]},W=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ma.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function Oa(a){return this.fromWireType(K[a>>2])}
var Pa={name:"emscripten::val",fromWireType:a=>{var b=V(a);Na(a);return b},toWireType:(a,b)=>W(b),L:8,readValueFromPointer:Oa,K:null},Qa=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(la[c>>2])};case 8:return function(c){return this.fromWireType(ma[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ra=(a,b)=>Object.defineProperty(b,"name",{value:a}),Sa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ta(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].K)return!0;return!1}function Ua(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Ra(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
for(var Va=(a,b)=>{if(void 0===f[a].J){var c=f[a];f[a]=function(...d){if(!f[a].J.hasOwnProperty(d.length))throw new S(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].J})!`);return f[a].J[d.length].apply(this,d)};f[a].J=[];f[a].J[c.N]=c}},Wa=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].J&&void 0!==f[a].J[c])throw new S(`Cannot register public name '${a}' twice`);Va(a,a);if(f.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].J[c]=b}else f[a]=b,void 0!==c&&(f[a].R=c)},Xa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(K[b+4*d>>2]);return c},Ya=[],Za,$a=a=>{var b=Ya[a];b||(a>=Ya.length&&(Ya.length=a+1),Ya[a]=b=Za.get(a));return b},ab=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,f["dynCall_"+a])(b,...c)):b=$a(b)(...c);return b},db=(a,b)=>(...c)=>ab(a,b,c),eb=(a,b)=>{a=N(a);var c=a.includes("j")?db(a,b):$a(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c},fb,hb=
a=>{a=gb(a);var b=N(a);X(a);return b},ib=(a,b)=>{function c(k){e[k]||P[k]||(R[k]?R[k].forEach(c):(d.push(k),e[k]=!0))}var d=[],e={};b.forEach(c);throw new fb(`${a}: `+d.map(hb).join([", "]));},jb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},kb=(a,b,c)=>{switch(b){case 1:return c?d=>ka[d]:d=>G[d];case 2:return c?d=>H[d>>1]:d=>I[d>>1];case 4:return c?d=>J[d>>2]:d=>K[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},lb="undefined"!=typeof TextDecoder?new TextDecoder:
void 0,mb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,nb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&I[c];)++c;c<<=1;if(32<c-a&&mb)return mb.decode(G.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=H[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},ob=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)H[b>>1]=a.charCodeAt(e),b+=2;H[b>>1]=0;return b-d},pb=a=>2*a.length,qb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=
J[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},rb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var k=a.charCodeAt(e);if(55296<=k&&57343>=k){var l=a.charCodeAt(++e);k=65536+((k&1023)<<10)|l&1023}J[b>>2]=k;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d},sb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},tb=(a,b)=>{var c=P[a];if(void 0===
c)throw a=`${b} has unknown type ${hb(a)}`,new S(a);return c},ub=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(K[b>>2]=W(d));return a},vb=[],wb={},xb=a=>{var b=wb[a];return void 0===b?N(a):b},yb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),zb=a=>{var b=vb.length;vb.push(a);return b},Ab=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=tb(K[b+4*d>>2],"parameter "+d);return c},Y={},Bb=0,Cb=a=>{ja=a;Da||0<Bb||(f.onExit?.(a),E=!0);t(a,new Ba(a))},Db=a=>{if(!E)try{if(a(),!(Da||0<
Bb))try{ja=a=ja,Cb(a)}catch(b){b instanceof Ba||"unwind"==b||t(1,b)}}catch(b){b instanceof Ba||"unwind"==b||t(1,b)}},Eb=Array(256),Fb=0;256>Fb;++Fb)Eb[Fb]=String.fromCharCode(Fb);Ha=Eb;S=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Ja=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};U.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>U.length/2-5-Ma.length;
fb=f.UnboundTypeError=((a,b)=>{var c=Ra(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Ib={m:(a,b,c)=>{var d=new Ea(a);K[d.M+16>>2]=0;K[d.M+4>>2]=b;K[d.M+8>>2]=c;Fa=a;Ga++;throw Fa;},t:()=>{ta("")},p:()=>{},x:(a,b,c,d)=>{b=N(b);T(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,k){return k?c:d},L:8,readValueFromPointer:function(e){return this.fromWireType(G[e])},K:null})},w:a=>T(a,Pa),j:(a,b,c)=>{b=N(b);T(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,L:8,readValueFromPointer:Qa(b,c),K:null})},i:(a,b,c,d,e,k,l)=>{var g=Xa(b,c);a=N(a);a=jb(a);e=eb(d,e);Wa(a,function(){ib(`Cannot call ${a} due to unbound types`,
g)},b-1);Ka(g,m=>{var h=[m[0],null].concat(m.slice(1));m=a;var n=a;var q=e,p=h.length;if(2>p)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var w=null!==h[1]&&!1,F=Ta(h),z="void"!==h[0].name;q=[n,Ia,q,k,Sa,h[0],h[1]];for(var A=0;A<p-2;++A)q.push(h[A+2]);if(!F)for(A=w?1:2;A<h.length;++A)null!==h[A].K&&q.push(h[A].K);F=Ta(h);A=h.length-2;var v=[],Q=["fn"];w&&Q.push("thisWired");for(p=0;p<A;++p)v.push(`arg${p}`),Q.push(`arg${p}Wired`);v=v.join(",");Q=Q.join(",");
v=`return function (${v}) {\n`;F&&(v+="var destructors = [];\n");var bb=F?"destructors":"null",ya="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");w&&(v+=`var thisWired = classParam['toWireType'](${bb}, this);\n`);for(p=0;p<A;++p)v+=`var arg${p}Wired = argType${p}['toWireType'](${bb}, arg${p});\n`,ya.push(`argType${p}`);v+=(z||l?"var rv = ":"")+`invoker(${Q});\n`;if(F)v+="runDestructors(destructors);\n";else for(p=w?1:2;p<h.length;++p)w=1===p?"thisWired":"arg"+
(p-2)+"Wired",null!==h[p].K&&(v+=`${w}_dtor(${w});\n`,ya.push(`${w}_dtor`));z&&(v+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [cb,Kb]=[ya,v+"}\n"];cb.push(Kb);h=Ua(cb)(...q);n=Ra(n,h);h=b-1;if(!f.hasOwnProperty(m))throw new Ja("Replacing nonexistent public symbol");void 0!==f[m].J&&void 0!==h?f[m].J[h]=n:(f[m]=n,f[m].N=h);return[]})},b:(a,b,c,d,e)=>{b=N(b);-1===e&&(e=4294967295);e=g=>g;if(0===d){var k=32-8*c;e=g=>g<<k>>>k}var l=b.includes("unsigned")?function(g,m){return m>>>0}:
function(g,m){return m};T(a,{name:b,fromWireType:e,toWireType:l,L:8,readValueFromPointer:kb(b,c,0!==d),K:null})},a:(a,b,c)=>{function d(k){return new e(ka.buffer,K[k+4>>2],K[k>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);T(a,{name:c,fromWireType:d,L:8,readValueFromPointer:d},{O:!0})},k:(a,b)=>{b=N(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=K[d>>2],k=d+4;if(c)for(var l=k,g=0;g<=e;++g){var m=k+g;if(g==
e||0==G[m]){if(l){var h=l;var n=G,q=h+(m-l);for(l=h;n[l]&&!(l>=q);)++l;if(16<l-h&&n.buffer&&lb)h=lb.decode(n.subarray(h,l));else{for(q="";h<l;){var p=n[h++];if(p&128){var w=n[h++]&63;if(192==(p&224))q+=String.fromCharCode((p&31)<<6|w);else{var F=n[h++]&63;p=224==(p&240)?(p&15)<<12|w<<6|F:(p&7)<<18|w<<12|F<<6|n[h++]&63;65536>p?q+=String.fromCharCode(p):(p-=65536,q+=String.fromCharCode(55296|p>>10,56320|p&1023))}}else q+=String.fromCharCode(p)}h=q}}else h="";if(void 0===z)var z=h;else z+=String.fromCharCode(0),
z+=h;l=m+1}}else{z=Array(e);for(g=0;g<e;++g)z[g]=String.fromCharCode(G[k+g]);z=z.join("")}X(d);return z},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var k,l="string"==typeof e;if(!(l||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new S("Cannot pass non-string to std::string");var g;if(c&&l)for(k=g=0;k<e.length;++k){var m=e.charCodeAt(k);127>=m?g++:2047>=m?g+=2:55296<=m&&57343>=m?(g+=4,++k):g+=3}else g=e.length;k=g;g=Gb(4+k+1);m=
g+4;K[g>>2]=k;if(c&&l){if(l=m,m=k+1,k=G,0<m){m=l+m-1;for(var h=0;h<e.length;++h){var n=e.charCodeAt(h);if(55296<=n&&57343>=n){var q=e.charCodeAt(++h);n=65536+((n&1023)<<10)|q&1023}if(127>=n){if(l>=m)break;k[l++]=n}else{if(2047>=n){if(l+1>=m)break;k[l++]=192|n>>6}else{if(65535>=n){if(l+2>=m)break;k[l++]=224|n>>12}else{if(l+3>=m)break;k[l++]=240|n>>18;k[l++]=128|n>>12&63}k[l++]=128|n>>6&63}k[l++]=128|n&63}}k[l]=0}}else if(l)for(l=0;l<k;++l){h=e.charCodeAt(l);if(255<h)throw X(m),new S("String has UTF-16 code units that do not fit in 8 bits");
G[m+l]=h}else for(l=0;l<k;++l)G[m+l]=e[l];null!==d&&d.push(X,g);return g},L:8,readValueFromPointer:Oa,K(d){X(d)}})},e:(a,b,c)=>{c=N(c);if(2===b){var d=nb;var e=ob;var k=pb;var l=g=>I[g>>1]}else 4===b&&(d=qb,e=rb,k=sb,l=g=>K[g>>2]);T(a,{name:c,fromWireType:g=>{for(var m=K[g>>2],h,n=g+4,q=0;q<=m;++q){var p=g+4+q*b;if(q==m||0==l(p))n=d(n,p-n),void 0===h?h=n:(h+=String.fromCharCode(0),h+=n),n=p+b}X(g);return h},toWireType:(g,m)=>{if("string"!=typeof m)throw new S(`Cannot pass non-string to C++ string type ${c}`);
var h=k(m),n=Gb(4+h+b);K[n>>2]=h/b;e(m,n+4,h+b);null!==g&&g.push(X,n);return n},L:8,readValueFromPointer:Oa,K(g){X(g)}})},y:(a,b)=>{b=N(b);T(a,{P:!0,name:b,L:0,fromWireType:()=>{},toWireType:()=>{}})},v:(a,b,c)=>G.copyWithin(a,b,b+c),r:()=>{Da=!1;Bb=0},n:(a,b,c)=>{a=V(a);b=tb(b,"emval::as");return ub(b,c,a)},o:(a,b,c,d)=>{a=vb[a];b=V(b);return a(null,b,c,d)},z:(a,b,c,d,e)=>{a=vb[a];b=V(b);c=xb(c);return a(b,b[c],d,e)},c:Na,B:a=>{if(0===a)return W(yb());a=xb(a);return W(yb()[a])},f:(a,b,c)=>{b=Ab(a,
b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",k=0,l=[];0===c&&l.push("obj");for(var g=["retType"],m=[d],h=0;h<a;++h)l.push("arg"+h),g.push("argType"+h),m.push(b[h]),e+=`  var arg${h} = argType${h}.readValueFromPointer(args${k?"+"+k:""});\n`,k+=b[h].L;e+=`  var rv = ${1===c?"new func":"func.call"}(${l.join(", ")});\n`;d.P||(g.push("emval_returnValue"),m.push(ub),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");g.push(e+"};\n");a=Ua(g)(...m);c=
`methodCaller<(${b.map(n=>n.name).join(", ")}) => ${d.name}>`;return zb(Ra(c,a))},h:(a,b)=>{a=V(a);b=V(b);return W(a[b])},A:a=>{9<a&&(U[a+1]+=1)},g:a=>W(xb(a)),d:a=>{var b=V(a);Sa(b);Na(a)},l:(a,b)=>{a=tb(a,"_emval_take_value");a=a.readValueFromPointer(b);return W(a)},s:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];Db(()=>Hb(a,performance.now()))},b);Y[a]={id:c,S:b};return 0},u:a=>{var b=G.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=
2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-D.buffer.byteLength+65535)/65536;try{D.grow(d);na();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},q:Cb},Z=function(){function a(c){Z=c.exports;D=Z.C;na();Za=Z.H;pa.unshift(Z.D);L--;f.monitorRunDependencies?.(L);0==L&&(null!==sa&&(clearInterval(sa),sa=null),M&&(c=M,M=null,c()));return Z}var b={a:Ib};L++;f.monitorRunDependencies?.(L);if(f.instantiateWasm)try{return f.instantiateWasm(b,
a)}catch(c){B(`Module.instantiateWasm callback failed with error: ${c}`),r(c)}va??=f.locateFile?ua("countup.wasm")?"countup.wasm":f.locateFile?f.locateFile("countup.wasm",u):u+"countup.wasm":(new URL("countup.wasm",import.meta.url)).href;Aa(b,function(c){a(c.instance)}).catch(r);return{}}(),gb=a=>(gb=Z.E)(a),Hb=(a,b)=>(Hb=Z.F)(a,b),Gb=a=>(Gb=Z.G)(a),X=a=>(X=Z.I)(a),Jb;M=function Lb(){Jb||Mb();Jb||(M=Lb)};
function Mb(){function a(){if(!Jb&&(Jb=!0,f.calledRun=!0,!E)){Ca(pa);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();qa.unshift(b)}Ca(qa)}}if(!(0<L)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ra();Ca(oa);0<L||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Mb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default Module;
