
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var n=moduleArg,ba,ca,da=new Promise((a,b)=>{ba=a;ca=b}),ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(ha){const {createRequire:a}=await import("module");let b=import.meta.url;b.startsWith("data:")&&(b="/");var require=a(b)}var ia=Object.assign({},n),ja=(a,b)=>{throw b;},p="",ka,la;
if(ha){var fs=require("fs"),ma=require("path");import.meta.url.startsWith("data:")||(p=ma.dirname(require("url").fileURLToPath(import.meta.url))+"/");la=a=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a)};ka=a=>{a=na(a)?new URL(a):ma.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};process.argv.slice(2);ja=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||fa)fa?p=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(p=document.currentScript.src),_scriptName&&(p=_scriptName),p.startsWith("blob:")?p="":p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1),fa&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=a=>na(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));n.print||console.log.bind(console);var w=n.printErr||console.error.bind(console);Object.assign(n,ia);ia=null;var oa=n.wasmBinary,pa,qa=!1,ra,sa,x,y,ta,A,B,ua,va;
function wa(){var a=pa.buffer;n.HEAP8=sa=new Int8Array(a);n.HEAP16=y=new Int16Array(a);n.HEAPU8=x=new Uint8Array(a);n.HEAPU16=ta=new Uint16Array(a);n.HEAP32=A=new Int32Array(a);n.HEAPU32=B=new Uint32Array(a);n.HEAPF32=ua=new Float32Array(a);n.HEAPF64=va=new Float64Array(a)}var xa=[],ya=[],za=[];function Aa(){var a=n.preRun.shift();xa.unshift(a)}var C=0,Ba=null,D=null;
function Ca(a){n.onAbort?.(a);a="Aborted("+a+")";w(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}var Da=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ea;function Fa(a){if(a==Ea&&oa)return new Uint8Array(oa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}function Ga(a){return oa?Promise.resolve().then(()=>Fa(a)):ka(a).then(b=>new Uint8Array(b),()=>Fa(a))}
function Ha(a,b,c){return Ga(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{w(`failed to asynchronously prepare wasm: ${d}`);Ca(d)})}function Ia(a,b){var c=Ea;return oa||"function"!=typeof WebAssembly.instantiateStreaming||Da(c)||na(c)||ha||"function"!=typeof fetch?Ha(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){w(`wasm streaming compile failed: ${e}`);w("falling back to ArrayBuffer instantiation");return Ha(c,a,b)}))}
function Ja(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ka=a=>{for(;0<a.length;)a.shift()(n)},La=n.noExitRuntime||!0;class Ma{constructor(a){this.R=a-24}}var Na=0,Oa=0,Pa={},Ra=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function E(a){return this.fromWireType(B[a>>2])}
var G={},H={},Sa={},I,K=(a,b,c)=>{function d(f){f=c(f);if(f.length!==a.length)throw new I("Mismatched type converter count");for(var m=0;m<a.length;++m)J(a[m],f[m])}a.forEach(f=>Sa[f]=b);var e=Array(b.length),h=[],g=0;b.forEach((f,m)=>{H.hasOwnProperty(f)?e[m]=H[f]:(h.push(f),G.hasOwnProperty(f)||(G[f]=[]),G[f].push(()=>{e[m]=H[f];++g;g===h.length&&d(e)}))});0===h.length&&d(e)},Ta,L=a=>{for(var b="";x[a];)b+=Ta[x[a++]];return b},M,Ua=a=>{throw new M(a);};
function Va(a,b,c={}){var d=b.name;if(!a)throw new M(`type "${d}" must have a positive integer typeid pointer`);if(H.hasOwnProperty(a)){if(c.wa)return;throw new M(`Cannot register type '${d}' twice`);}H[a]=b;delete Sa[a];G.hasOwnProperty(a)&&(b=G[a],delete G[a],b.forEach(e=>e()))}function J(a,b,c={}){return Va(a,b,c)}
var Wa=a=>{throw new M(a.O.S.P.name+" instance already deleted");},Xa=!1,Ya=()=>{},Za=(a,b,c)=>{if(b===c)return a;if(void 0===c.U)return null;a=Za(a,b,c.U);return null===a?null:c.pa(a)},$a={},N=[],ab=()=>{for(;N.length;){var a=N.pop();a.O.aa=!1;a["delete"]()}},O,P={},bb=(a,b)=>{if(void 0===b)throw new M("ptr should not be undefined");for(;a.U;)b=a.ea(b),a=a.U;return P[b]},cb=(a,b)=>{if(!b.S||!b.R)throw new I("makeClassHandle requires ptr and ptrType");if(!!b.V!==!!b.T)throw new I("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return Q(Object.create(a,{O:{value:b,writable:!0}}))},Q=a=>{if("undefined"===typeof FinalizationRegistry)return Q=b=>b,a;Xa=new FinalizationRegistry(b=>{b=b.O;--b.count.value;0===b.count.value&&(b.T?b.V.Y(b.T):b.S.P.Y(b.R))});Q=b=>{var c=b.O;c.T&&Xa.register(b,{O:c},b);return b};Ya=b=>{Xa.unregister(b)};return Q(a)};function db(){}
var R=(a,b)=>Object.defineProperty(b,"name",{value:a}),eb=(a,b,c)=>{if(void 0===a[b].Z){var d=a[b];a[b]=function(...e){if(!a[b].Z.hasOwnProperty(e.length))throw new M(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Z})!`);return a[b].Z[e.length].apply(this,e)};a[b].Z=[];a[b].Z[d.fa]=d}},fb=(a,b)=>{if(n.hasOwnProperty(a))throw new M(`Cannot register public name '${a}' twice`);n[a]=b},gb=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,
"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function hb(a,b,c,d,e,h,g,f){this.name=a;this.constructor=b;this.ba=c;this.Y=d;this.U=e;this.ra=h;this.ea=g;this.pa=f;this.za=[]}var ib=(a,b,c)=>{for(;b!==c;){if(!b.ea)throw new M(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ea(a);b=b.U}return a};
function jb(a,b){if(null===b){if(this.ia)throw new M(`null is not a valid ${this.name}`);return 0}if(!b.O)throw new M(`Cannot pass "${kb(b)}" as a ${this.name}`);if(!b.O.R)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);return ib(b.O.R,b.O.S.P,this.P)}
function lb(a,b){if(null===b){if(this.ia)throw new M(`null is not a valid ${this.name}`);if(this.ha){var c=this.ja();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.O)throw new M(`Cannot pass "${kb(b)}" as a ${this.name}`);if(!b.O.R)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ga&&b.O.S.ga)throw new M(`Cannot convert argument of type ${b.O.V?b.O.V.name:b.O.S.name} to parameter type ${this.name}`);c=ib(b.O.R,b.O.S.P,this.P);if(this.ha){if(void 0===b.O.T)throw new M("Passing raw pointer to smart pointer is illegal");
switch(this.Ea){case 0:if(b.O.V===this)c=b.O.T;else throw new M(`Cannot convert argument of type ${b.O.V?b.O.V.name:b.O.S.name} to parameter type ${this.name}`);break;case 1:c=b.O.T;break;case 2:if(b.O.V===this)c=b.O.T;else{var d=b.clone();c=this.Aa(c,S(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new M("Unsupporting sharing policy");}}return c}
function mb(a,b){if(null===b){if(this.ia)throw new M(`null is not a valid ${this.name}`);return 0}if(!b.O)throw new M(`Cannot pass "${kb(b)}" as a ${this.name}`);if(!b.O.R)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.O.S.ga)throw new M(`Cannot convert argument of type ${b.O.S.name} to parameter type ${this.name}`);return ib(b.O.R,b.O.S.P,this.P)}
function nb(a,b,c,d,e,h,g,f,m,k,l){this.name=a;this.P=b;this.ia=c;this.ga=d;this.ha=e;this.ya=h;this.Ea=g;this.na=f;this.ja=m;this.Aa=k;this.Y=l;e||void 0!==b.U?this.toWireType=lb:(this.toWireType=d?jb:mb,this.W=null)}
var ob=(a,b)=>{if(!n.hasOwnProperty(a))throw new I("Replacing nonexistent public symbol");n[a]=b;n[a].fa=void 0},pb=[],qb,rb=a=>{var b=pb[a];b||(a>=pb.length&&(pb.length=a+1),pb[a]=b=qb.get(a));return b},sb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,n["dynCall_"+a])(b,...c)):b=rb(b)(...c);return b},tb=(a,b)=>(...c)=>sb(a,b,c),T=(a,b)=>{a=L(a);var c=a.includes("j")?tb(a,b):rb(b);if("function"!=typeof c)throw new M(`unknown function pointer with signature ${a}: ${b}`);return c},ub,wb=
a=>{a=vb(a);var b=L(a);U(a);return b},yb=(a,b)=>{function c(h){e[h]||H[h]||(Sa[h]?Sa[h].forEach(c):(d.push(h),e[h]=!0))}var d=[],e={};b.forEach(c);throw new ub(`${a}: `+d.map(wb).join([", "]));},zb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B[b+4*d>>2]);return c};function Ab(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].W)return!0;return!1}
function Bb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=R(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Cb(a,b,c,d,e,h){var g=b.length;if(2>g)throw new M("argTypes array size mismatch! Must at least get return value and 'this' types!");var f=null!==b[1]&&null!==c,m=Ab(b);c="void"!==b[0].name;d=[a,Ua,d,e,Ra,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!m)for(e=f?1:2;e<b.length;++e)null!==b[e].W&&d.push(b[e].W);m=Ab(b);e=b.length-2;var k=[],l=["fn"];f&&l.push("thisWired");for(g=0;g<e;++g)k.push(`arg${g}`),l.push(`arg${g}Wired`);k=k.join(",");l=l.join(",");k=`return function (${k}) {\n`;m&&
(k+="var destructors = [];\n");var r=m?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");f&&(k+=`var thisWired = classParam['toWireType'](${r}, this);\n`);for(g=0;g<e;++g)k+=`var arg${g}Wired = argType${g}['toWireType'](${r}, arg${g});\n`,q.push(`argType${g}`);k+=(c||h?"var rv = ":"")+`invoker(${l});\n`;if(m)k+="runDestructors(destructors);\n";else for(g=f?1:2;g<b.length;++g)h=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].W&&(k+=`${h}_dtor(${h});\n`,
q.push(`${h}_dtor`));c&&(k+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [v,u]=[q,k+"}\n"];v.push(u);b=Bb(v)(...d);return R(a,b)}
var Db=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Eb=[],V=[],Fb=a=>{9<a&&0===--V[a+1]&&(V[a]=void 0,Eb.push(a))},W=a=>{if(!a)throw new M("Cannot use deleted val. handle = "+a);return V[a]},S=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Eb.pop()||V.length;V[b]=a;V[b+1]=1;return b}},Gb={name:"emscripten::val",fromWireType:a=>{var b=W(a);Fb(a);return b},toWireType:(a,b)=>S(b),X:8,readValueFromPointer:E,W:null},kb=a=>
{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Hb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ua[c>>2])};case 8:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ib=(a,b,c)=>{switch(b){case 1:return c?d=>sa[d]:d=>x[d];case 2:return c?d=>y[d>>1]:d=>ta[d>>1];case 4:return c?d=>A[d>>2]:d=>B[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},Jb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Kb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Lb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&Kb)return Kb.decode(x.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=y[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Mb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},Nb=a=>
2*a.length,Ob=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Pb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var g=a.charCodeAt(++e);h=65536+((h&1023)<<10)|g&1023}A[b>>2]=h;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d},Qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&
57343>=d&&++c;b+=4}return b},Rb=(a,b)=>{var c=H[a];if(void 0===c)throw a=`${b} has unknown type ${wb(a)}`,new M(a);return c},Sb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(B[b>>2]=S(d));return a},Tb=[],Ub={},Vb=a=>{var b=Ub[a];return void 0===b?L(a):b},Wb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),Xb=a=>{var b=Tb.length;Tb.push(a);return b},Yb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Rb(B[b+4*d>>2],"parameter "+d);return c},X={},Zb=0,$b=a=>{ra=a;La||0<Zb||(n.onExit?.(a),
qa=!0);ja(a,new Ja(a))},ac=a=>{if(!qa)try{if(a(),!(La||0<Zb))try{ra=a=ra,$b(a)}catch(b){b instanceof Ja||"unwind"==b||ja(1,b)}}catch(b){b instanceof Ja||"unwind"==b||ja(1,b)}};I=n.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var bc=Array(256),cc=0;256>cc;++cc)bc[cc]=String.fromCharCode(cc);Ta=bc;M=n.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(db.prototype,{isAliasOf:function(a){if(!(this instanceof db&&a instanceof db))return!1;var b=this.O.S.P,c=this.O.R;a.O=a.O;var d=a.O.S.P;for(a=a.O.R;b.U;)c=b.ea(c),b=b.U;for(;d.U;)a=d.ea(a),d=d.U;return b===d&&c===a},clone:function(){this.O.R||Wa(this);if(this.O.da)return this.O.count.value+=1,this;var a=Q,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.O;a=a(c.call(b,d,{O:{value:{count:e.count,aa:e.aa,da:e.da,R:e.R,S:e.S,T:e.T,V:e.V}}}));a.O.count.value+=1;a.O.aa=!1;return a},
["delete"](){this.O.R||Wa(this);if(this.O.aa&&!this.O.da)throw new M("Object already scheduled for deletion");Ya(this);var a=this.O;--a.count.value;0===a.count.value&&(a.T?a.V.Y(a.T):a.S.P.Y(a.R));this.O.da||(this.O.T=void 0,this.O.R=void 0)},isDeleted:function(){return!this.O.R},deleteLater:function(){this.O.R||Wa(this);if(this.O.aa&&!this.O.da)throw new M("Object already scheduled for deletion");N.push(this);1===N.length&&O&&O(ab);this.O.aa=!0;return this}});n.getInheritedInstanceCount=()=>Object.keys(P).length;
n.getLiveInheritedInstances=()=>{var a=[],b;for(b in P)P.hasOwnProperty(b)&&a.push(P[b]);return a};n.flushPendingDeletes=ab;n.setDelayFunction=a=>{O=a;N.length&&O&&O(ab)};
Object.assign(nb.prototype,{sa(a){this.na&&(a=this.na(a));return a},la(a){this.Y?.(a)},X:8,readValueFromPointer:E,fromWireType:function(a){function b(){return this.ha?cb(this.P.ba,{S:this.ya,R:c,V:this,T:a}):cb(this.P.ba,{S:this,R:a})}var c=this.sa(a);if(!c)return this.la(a),null;var d=bb(this.P,c);if(void 0!==d){if(0===d.O.count.value)return d.O.R=c,d.O.T=a,d.clone();d=d.clone();this.la(a);return d}d=this.P.ra(c);d=$a[d];if(!d)return b.call(this);d=this.ga?d.oa:d.pointerType;var e=Za(c,this.P,d.P);
return null===e?b.call(this):this.ha?cb(d.P.ba,{S:d,R:e,V:this,T:a}):cb(d.P.ba,{S:d,R:e})}});ub=n.UnboundTypeError=((a,b)=>{var c=R(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
V.push(0,1,void 0,1,null,1,!0,1,!1,1);n.count_emval_handles=()=>V.length/2-5-Eb.length;
var fc={l:(a,b,c)=>{var d=new Ma(a);B[d.R+16>>2]=0;B[d.R+4>>2]=b;B[d.R+8>>2]=c;Na=a;Oa++;throw Na;},w:()=>{Ca("")},A:a=>{var b=Pa[a];delete Pa[a];var c=b.ja,d=b.Y,e=b.ma,h=e.map(g=>g.va).concat(e.map(g=>g.Ca));K([a],h,g=>{var f={};e.forEach((m,k)=>{var l=g[k],r=m.ta,q=m.ua,v=g[k+e.length],u=m.Ba,t=m.Da;f[m.qa]={read:F=>l.fromWireType(r(q,F)),write:(F,Z)=>{var z=[];u(t,F,v.toWireType(z,Z));Ra(z)}}});return[{name:b.name,fromWireType:m=>{var k={},l;for(l in f)k[l]=f[l].read(m);d(m);return k},toWireType:(m,
k)=>{for(var l in f)if(!(l in k))throw new TypeError(`Missing field: "${l}"`);var r=c();for(l in f)f[l].write(r,k[l]);null!==m&&m.push(d,r);return r},X:8,readValueFromPointer:E,W:d}]})},r:()=>{},B:(a,b,c,d)=>{b=L(b);J(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,h){return h?c:d},X:8,readValueFromPointer:function(e){return this.fromWireType(x[e])},W:null})},u:(a,b,c,d,e,h,g,f,m,k,l,r,q)=>{l=L(l);h=T(e,h);f&&=T(g,f);k&&=T(m,k);q=T(r,q);var v=gb(l);fb(v,function(){yb(`Cannot construct ${l} due to unbound types`,
[d])});K([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var t=u.P;var F=t.ba}else F=db.prototype;u=R(l,function(...Qa){if(Object.getPrototypeOf(this)!==Z)throw new M("Use 'new' to construct "+l);if(void 0===z.$)throw new M(l+" has no accessible constructor");var xb=z.$[Qa.length];if(void 0===xb)throw new M(`Tried to invoke ctor of ${l} with invalid number of parameters (${Qa.length}) - expected (${Object.keys(z.$).toString()}) parameters instead!`);return xb.apply(this,Qa)});var Z=Object.create(F,{constructor:{value:u}});
u.prototype=Z;var z=new hb(l,u,Z,q,t,h,f,k);if(z.U){var aa;(aa=z.U).ka??(aa.ka=[]);z.U.ka.push(z)}t=new nb(l,z,!0,!1,!1);aa=new nb(l+"*",z,!1,!1,!1);F=new nb(l+" const*",z,!1,!0,!1);$a[a]={pointerType:aa,oa:F};ob(v,u);return[t,aa,F]})},q:(a,b,c,d,e,h)=>{var g=zb(b,c);e=T(d,e);K([],[a],f=>{f=f[0];var m=`constructor ${f.name}`;void 0===f.P.$&&(f.P.$=[]);if(void 0!==f.P.$[b-1])throw new M(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
f.P.$[b-1]=()=>{yb(`Cannot construct ${f.name} due to unbound types`,g)};K([],g,k=>{k.splice(1,0,null);f.P.$[b-1]=Cb(m,k,null,e,h);return[]});return[]})},k:(a,b,c,d,e,h,g,f,m)=>{var k=zb(c,d);b=L(b);b=Db(b);h=T(e,h);K([],[a],l=>{function r(){yb(`Cannot call ${q} due to unbound types`,k)}l=l[0];var q=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);f&&l.P.za.push(b);var v=l.P.ba,u=v[b];void 0===u||void 0===u.Z&&u.className!==l.name&&u.fa===c-2?(r.fa=c-2,r.className=l.name,v[b]=r):(eb(v,
b,q),v[b].Z[c-2]=r);K([],k,t=>{t=Cb(q,t,l,h,g,m);void 0===v[b].Z?(t.fa=c-2,v[b]=t):v[b].Z[c-2]=t;return[]});return[]})},z:a=>J(a,Gb),i:(a,b,c)=>{b=L(b);J(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,X:8,readValueFromPointer:Hb(b,c),W:null})},c:(a,b,c,d,e)=>{b=L(b);-1===e&&(e=4294967295);e=f=>f;if(0===d){var h=32-8*c;e=f=>f<<h>>>h}var g=b.includes("unsigned")?function(f,m){return m>>>0}:function(f,m){return m};J(a,{name:b,fromWireType:e,toWireType:g,X:8,readValueFromPointer:Ib(b,c,0!==d),W:null})},
a:(a,b,c)=>{function d(h){return new e(sa.buffer,B[h+4>>2],B[h>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=L(c);J(a,{name:c,fromWireType:d,X:8,readValueFromPointer:d},{wa:!0})},j:(a,b)=>{b=L(b);var c="std::string"===b;J(a,{name:b,fromWireType:function(d){var e=B[d>>2],h=d+4;if(c)for(var g=h,f=0;f<=e;++f){var m=h+f;if(f==e||0==x[m]){if(g){var k=g;var l=x,r=k+(m-g);for(g=k;l[g]&&!(g>=r);)++g;if(16<g-k&&l.buffer&&Jb)k=Jb.decode(l.subarray(k,
g));else{for(r="";k<g;){var q=l[k++];if(q&128){var v=l[k++]&63;if(192==(q&224))r+=String.fromCharCode((q&31)<<6|v);else{var u=l[k++]&63;q=224==(q&240)?(q&15)<<12|v<<6|u:(q&7)<<18|v<<12|u<<6|l[k++]&63;65536>q?r+=String.fromCharCode(q):(q-=65536,r+=String.fromCharCode(55296|q>>10,56320|q&1023))}}else r+=String.fromCharCode(q)}k=r}}else k="";if(void 0===t)var t=k;else t+=String.fromCharCode(0),t+=k;g=m+1}}else{t=Array(e);for(f=0;f<e;++f)t[f]=String.fromCharCode(x[h+f]);t=t.join("")}U(d);return t},toWireType:function(d,
e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,g="string"==typeof e;if(!(g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new M("Cannot pass non-string to std::string");var f;if(c&&g)for(h=f=0;h<e.length;++h){var m=e.charCodeAt(h);127>=m?f++:2047>=m?f+=2:55296<=m&&57343>=m?(f+=4,++h):f+=3}else f=e.length;h=f;f=dc(4+h+1);m=f+4;B[f>>2]=h;if(c&&g){if(g=m,m=h+1,h=x,0<m){m=g+m-1;for(var k=0;k<e.length;++k){var l=e.charCodeAt(k);if(55296<=l&&57343>=l){var r=
e.charCodeAt(++k);l=65536+((l&1023)<<10)|r&1023}if(127>=l){if(g>=m)break;h[g++]=l}else{if(2047>=l){if(g+1>=m)break;h[g++]=192|l>>6}else{if(65535>=l){if(g+2>=m)break;h[g++]=224|l>>12}else{if(g+3>=m)break;h[g++]=240|l>>18;h[g++]=128|l>>12&63}h[g++]=128|l>>6&63}h[g++]=128|l&63}}h[g]=0}}else if(g)for(g=0;g<h;++g){k=e.charCodeAt(g);if(255<k)throw U(m),new M("String has UTF-16 code units that do not fit in 8 bits");x[m+g]=k}else for(g=0;g<h;++g)x[m+g]=e[g];null!==d&&d.push(U,f);return f},X:8,readValueFromPointer:E,
W(d){U(d)}})},e:(a,b,c)=>{c=L(c);if(2===b){var d=Lb;var e=Mb;var h=Nb;var g=f=>ta[f>>1]}else 4===b&&(d=Ob,e=Pb,h=Qb,g=f=>B[f>>2]);J(a,{name:c,fromWireType:f=>{for(var m=B[f>>2],k,l=f+4,r=0;r<=m;++r){var q=f+4+r*b;if(r==m||0==g(q))l=d(l,q-l),void 0===k?k=l:(k+=String.fromCharCode(0),k+=l),l=q+b}U(f);return k},toWireType:(f,m)=>{if("string"!=typeof m)throw new M(`Cannot pass non-string to C++ string type ${c}`);var k=h(m),l=dc(4+k+b);B[l>>2]=k/b;e(m,l+4,k+b);null!==f&&f.push(U,l);return l},X:8,readValueFromPointer:E,
W(f){U(f)}})},G:(a,b,c,d,e,h)=>{Pa[a]={name:L(b),ja:T(c,d),Y:T(e,h),ma:[]}},d:(a,b,c,d,e,h,g,f,m,k)=>{Pa[a].ma.push({qa:L(b),va:c,ta:T(d,e),ua:h,Ca:g,Ba:T(f,m),Da:k})},C:(a,b)=>{b=L(b);J(a,{xa:!0,name:b,X:0,fromWireType:()=>{},toWireType:()=>{}})},y:(a,b,c)=>x.copyWithin(a,b,b+c),t:()=>{La=!1;Zb=0},F:(a,b,c)=>{a=W(a);b=Rb(b,"emval::as");return Sb(b,c,a)},o:(a,b,c,d)=>{a=Tb[a];b=W(b);return a(null,b,c,d)},D:(a,b,c,d,e)=>{a=Tb[a];b=W(b);c=Vb(c);return a(b,b[c],d,e)},b:Fb,p:a=>{if(0===a)return S(Wb());
a=Vb(a);return S(Wb()[a])},g:(a,b,c)=>{b=Yb(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",h=0,g=[];0===c&&g.push("obj");for(var f=["retType"],m=[d],k=0;k<a;++k)g.push("arg"+k),f.push("argType"+k),m.push(b[k]),e+=`  var arg${k} = argType${k}.readValueFromPointer(args${h?"+"+h:""});\n`,h+=b[k].X;e+=`  var rv = ${1===c?"new func":"func.call"}(${g.join(", ")});\n`;d.xa||(f.push("emval_returnValue"),m.push(Sb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");
f.push(e+"};\n");a=Bb(f)(...m);c=`methodCaller<(${b.map(l=>l.name).join(", ")}) => ${d.name}>`;return Xb(R(c,a))},n:(a,b)=>{a=W(a);b=W(b);return S(a[b])},h:a=>{9<a&&(V[a+1]+=1)},m:a=>S(Vb(a)),f:a=>{var b=W(a);Ra(b);Fb(a)},E:(a,b)=>{a=Rb(a,"_emval_take_value");a=a.readValueFromPointer(b);return S(a)},v:(a,b)=>{X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var c=setTimeout(()=>{delete X[a];ac(()=>ec(a,performance.now()))},b);X[a]={id:c,Fa:b};return 0},x:a=>{var b=x.length;a>>>=0;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536;try{pa.grow(d);wa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},s:$b},Y=function(){function a(c){Y=c.exports;pa=Y.H;wa();qb=Y.M;ya.unshift(Y.I);C--;n.monitorRunDependencies?.(C);0==C&&(null!==Ba&&(clearInterval(Ba),Ba=null),D&&(c=D,D=null,c()));return Y}var b={a:fc};C++;n.monitorRunDependencies?.(C);if(n.instantiateWasm)try{return n.instantiateWasm(b,
a)}catch(c){w(`Module.instantiateWasm callback failed with error: ${c}`),ca(c)}Ea??=n.locateFile?Da("init.wasm")?"init.wasm":n.locateFile?n.locateFile("init.wasm",p):p+"init.wasm":(new URL("init.wasm",import.meta.url)).href;Ia(b,function(c){a(c.instance)}).catch(ca);return{}}(),vb=a=>(vb=Y.J)(a),ec=(a,b)=>(ec=Y.K)(a,b),dc=a=>(dc=Y.L)(a),U=a=>(U=Y.N)(a),gc;D=function hc(){gc||ic();gc||(D=hc)};
function ic(){function a(){if(!gc&&(gc=!0,n.calledRun=!0,!qa)){Ka(ya);ba(n);n.onRuntimeInitialized?.();if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;){var b=n.postRun.shift();za.unshift(b)}Ka(za)}}if(!(0<C)){if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Aa();Ka(xa);0<C||(n.setStatus?(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);a()},1)):a())}}
if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.pop()();ic();moduleRtn=da;


  return moduleRtn;
}
);
})();
export default Module;
