
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var m=moduleArg,aa,p,ba=new Promise((a,b)=>{aa=a;p=b}),ca="object"==typeof window,da="undefined"!=typeof WorkerGlobalScope,ea=Object.assign({},m),u="",fa,ha;
if(ca||da)da?u=self.location.href:"undefined"!=typeof document&&document.currentScript&&(u=document.currentScript.src),_scriptName&&(u=_scriptName),u.startsWith("blob:")?u="":u=u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1),da&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var w=m.printErr||console.error.bind(console);Object.assign(m,ea);ea=null;var x=m.wasmBinary,ia,ja=!1,ka,la,A,B,ma,C,D,na,oa;function pa(){var a=ia.buffer;m.HEAP8=la=new Int8Array(a);m.HEAP16=B=new Int16Array(a);m.HEAPU8=A=new Uint8Array(a);m.HEAPU16=ma=new Uint16Array(a);m.HEAP32=C=new Int32Array(a);m.HEAPU32=D=new Uint32Array(a);m.HEAPF32=na=new Float32Array(a);m.HEAPF64=oa=new Float64Array(a)}var qa=[],ra=[],sa=[];function ta(){var a=m.preRun.shift();qa.unshift(a)}var E=0,G=null;
function ua(a){m.onAbort?.(a);a="Aborted("+a+")";w(a);ja=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");p(a);throw a;}var va=a=>a.startsWith("data:application/octet-stream;base64,"),wa;async function xa(a){if(!x)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==wa&&x)a=new Uint8Array(x);else if(ha)a=ha(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ya(a,b){try{var c=await xa(a);return await WebAssembly.instantiate(c,b)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}async function za(a){var b=wa;if(!x&&"function"==typeof WebAssembly.instantiateStreaming&&!va(b)&&"function"==typeof fetch)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return ya(b,a)}
class Aa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ba=a=>{for(;0<a.length;)a.shift()(m)},Ca=m.noExitRuntime||!0;class Da{constructor(a){this.R=a-24}}var Ea=0,Ga=0,Ha={},Ia=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function H(a){return this.fromWireType(D[a>>2])}
var I={},J={},Ja={},K,M=(a,b,c)=>{function d(f){f=c(f);if(f.length!==a.length)throw new K("Mismatched type converter count");for(var l=0;l<a.length;++l)L(a[l],f[l])}a.forEach(f=>Ja[f]=b);var e=Array(b.length),g=[],h=0;b.forEach((f,l)=>{J.hasOwnProperty(f)?e[l]=J[f]:(g.push(f),I.hasOwnProperty(f)||(I[f]=[]),I[f].push(()=>{e[l]=J[f];++h;h===g.length&&d(e)}))});0===g.length&&d(e)},Ka,N=a=>{for(var b="";A[a];)b+=Ka[A[a++]];return b},O,La=a=>{throw new O(a);};
function Ma(a,b,c={}){var d=b.name;if(!a)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(J.hasOwnProperty(a)){if(c.va)return;throw new O(`Cannot register type '${d}' twice`);}J[a]=b;delete Ja[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(e=>e()))}function L(a,b,c={}){return Ma(a,b,c)}
var Na=a=>{throw new O(a.O.S.P.name+" instance already deleted");},Oa=!1,Pa=()=>{},Qa=(a,b,c)=>{if(b===c)return a;if(void 0===c.U)return null;a=Qa(a,b,c.U);return null===a?null:c.oa(a)},Ra={},Sa={},Ta=(a,b)=>{if(void 0===b)throw new O("ptr should not be undefined");for(;a.U;)b=a.ea(b),a=a.U;return Sa[b]},Ua=(a,b)=>{if(!b.S||!b.R)throw new K("makeClassHandle requires ptr and ptrType");if(!!b.V!==!!b.T)throw new K("Both smartPtrType and smartPtr must be specified");b.count={value:1};return P(Object.create(a,
{O:{value:b,writable:!0}}))},P=a=>{if("undefined"===typeof FinalizationRegistry)return P=b=>b,a;Oa=new FinalizationRegistry(b=>{b=b.O;--b.count.value;0===b.count.value&&(b.T?b.V.Y(b.T):b.S.P.Y(b.R))});P=b=>{var c=b.O;c.T&&Oa.register(b,{O:c},b);return b};Pa=b=>{Oa.unregister(b)};return P(a)},Va=[];function Wa(){}
var Q=(a,b)=>Object.defineProperty(b,"name",{value:a}),Xa=(a,b,c)=>{if(void 0===a[b].Z){var d=a[b];a[b]=function(...e){if(!a[b].Z.hasOwnProperty(e.length))throw new O(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Z})!`);return a[b].Z[e.length].apply(this,e)};a[b].Z=[];a[b].Z[d.ba]=d}},Ya=(a,b)=>{if(m.hasOwnProperty(a))throw new O(`Cannot register public name '${a}' twice`);m[a]=b;m[a].ba=void 0},Za=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);
return 48<=b&&57>=b?`_${a}`:a};function $a(a,b,c,d,e,g,h,f){this.name=a;this.constructor=b;this.aa=c;this.Y=d;this.U=e;this.qa=g;this.ea=h;this.oa=f;this.ya=[]}var ab=(a,b,c)=>{for(;b!==c;){if(!b.ea)throw new O(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ea(a);b=b.U}return a};
function bb(a,b){if(null===b){if(this.ha)throw new O(`null is not a valid ${this.name}`);return 0}if(!b.O)throw new O(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.O.R)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);return ab(b.O.R,b.O.S.P,this.P)}
function db(a,b){if(null===b){if(this.ha)throw new O(`null is not a valid ${this.name}`);if(this.ga){var c=this.ia();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.O)throw new O(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.O.R)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.fa&&b.O.S.fa)throw new O(`Cannot convert argument of type ${b.O.V?b.O.V.name:b.O.S.name} to parameter type ${this.name}`);c=ab(b.O.R,b.O.S.P,this.P);if(this.ga){if(void 0===b.O.T)throw new O("Passing raw pointer to smart pointer is illegal");
switch(this.Da){case 0:if(b.O.V===this)c=b.O.T;else throw new O(`Cannot convert argument of type ${b.O.V?b.O.V.name:b.O.S.name} to parameter type ${this.name}`);break;case 1:c=b.O.T;break;case 2:if(b.O.V===this)c=b.O.T;else{var d=b.clone();c=this.za(c,R(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new O("Unsupporting sharing policy");}}return c}
function eb(a,b){if(null===b){if(this.ha)throw new O(`null is not a valid ${this.name}`);return 0}if(!b.O)throw new O(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.O.R)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.O.S.fa)throw new O(`Cannot convert argument of type ${b.O.S.name} to parameter type ${this.name}`);return ab(b.O.R,b.O.S.P,this.P)}
function fb(a,b,c,d,e,g,h,f,l,k,n){this.name=a;this.P=b;this.ha=c;this.fa=d;this.ga=e;this.xa=g;this.Da=h;this.ma=f;this.ia=l;this.za=k;this.Y=n;e||void 0!==b.U?this.toWireType=db:(this.toWireType=d?bb:eb,this.W=null)}
var gb=(a,b)=>{if(!m.hasOwnProperty(a))throw new K("Replacing nonexistent public symbol");m[a]=b;m[a].ba=void 0},hb=[],ib,jb=a=>{var b=hb[a];b||(a>=hb.length&&(hb.length=a+1),hb[a]=b=ib.get(a));return b},kb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,m["dynCall_"+a])(b,...c)):b=jb(b)(...c);return b},lb=(a,b)=>(...c)=>kb(a,b,c),S=(a,b)=>{a=N(a);var c=a.includes("j")?lb(a,b):jb(b);if("function"!=typeof c)throw new O(`unknown function pointer with signature ${a}: ${b}`);return c},mb,pb=
a=>{a=ob(a);var b=N(a);T(a);return b},qb=(a,b)=>{function c(g){e[g]||J[g]||(Ja[g]?Ja[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new mb(`${a}: `+d.map(pb).join([", "]));},rb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c};function sb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].W)return!0;return!1}
function tb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Q(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function ub(a,b,c,d,e,g){var h=b.length;if(2>h)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var f=null!==b[1]&&null!==c,l=sb(b);c="void"!==b[0].name;d=[a,La,d,e,Ia,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!l)for(e=f?1:2;e<b.length;++e)null!==b[e].W&&d.push(b[e].W);l=sb(b);e=b.length-2;var k=[],n=["fn"];f&&n.push("thisWired");for(h=0;h<e;++h)k.push(`arg${h}`),n.push(`arg${h}Wired`);k=k.join(",");n=n.join(",");k=`return function (${k}) {\n`;l&&
(k+="var destructors = [];\n");var q=l?"destructors":"null",r="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");f&&(k+=`var thisWired = classParam['toWireType'](${q}, this);\n`);for(h=0;h<e;++h)k+=`var arg${h}Wired = argType${h}['toWireType'](${q}, arg${h});\n`,r.push(`argType${h}`);k+=(c||g?"var rv = ":"")+`invoker(${n});\n`;if(l)k+="runDestructors(destructors);\n";else for(h=f?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].W&&(k+=`${g}_dtor(${g});\n`,
r.push(`${g}_dtor`));c&&(k+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [v,t]=[r,k+"}\n"];v.push(t);b=tb(v)(...d);return Q(a,b)}
var vb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},wb=[],U=[],xb=a=>{9<a&&0===--U[a+1]&&(U[a]=void 0,wb.push(a))},V=a=>{if(!a)throw new O("Cannot use deleted val. handle = "+a);return U[a]},R=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=wb.pop()||U.length;U[b]=a;U[b+1]=1;return b}},yb={name:"emscripten::val",fromWireType:a=>{var b=V(a);xb(a);return b},toWireType:(a,b)=>R(b),X:8,readValueFromPointer:H,W:null},cb=a=>
{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},zb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(na[c>>2])};case 8:return function(c){return this.fromWireType(oa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ab=(a,b,c)=>{switch(b){case 1:return c?d=>la[d]:d=>A[d];case 2:return c?d=>B[d>>1]:d=>ma[d>>1];case 4:return c?d=>C[d>>2]:d=>D[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},Bb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Cb=(a=0,b=NaN)=>{var c=A,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Bb)return Bb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Db="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Eb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ma[c];)++c;c<<=1;if(32<c-a&&Db)return Db.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Fb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d},Gb=a=>2*a.length,Hb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=C[a+
4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Ib=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}C[b>>2]=g;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},Jb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Kb=0,Lb=(a,b)=>{var c=J[a];if(void 0===
c)throw a=`${b} has unknown type ${pb(a)}`,new O(a);return c},Mb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(D[b>>2]=R(d));return a},Nb=[],Ob={},Pb=a=>{var b=Ob[a];return void 0===b?N(a):b},Qb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),Rb=a=>{var b=Nb.length;Nb.push(a);return b},Sb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Lb(D[b+4*d>>2],"parameter "+d);return c},Y={},Tb=a=>{if(!(a instanceof Aa||"unwind"==a))throw a;},Ub=a=>{ka=a;Ca||0<Kb||(m.onExit?.(a),ja=!0);
throw new Aa(a);},Vb=a=>{if(!ja)try{if(a(),!(Ca||0<Kb))try{ka=a=ka,Ub(a)}catch(b){Tb(b)}}catch(b){Tb(b)}};K=m.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Wb=Array(256),Xb=0;256>Xb;++Xb)Wb[Xb]=String.fromCharCode(Xb);Ka=Wb;O=m.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Wa.prototype,{isAliasOf:function(a){if(!(this instanceof Wa&&a instanceof Wa))return!1;var b=this.O.S.P,c=this.O.R;a.O=a.O;var d=a.O.S.P;for(a=a.O.R;b.U;)c=b.ea(c),b=b.U;for(;d.U;)a=d.ea(a),d=d.U;return b===d&&c===a},clone:function(){this.O.R||Na(this);if(this.O.da)return this.O.count.value+=1,this;var a=P,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.O;a=a(c.call(b,d,{O:{value:{count:e.count,ca:e.ca,da:e.da,R:e.R,S:e.S,T:e.T,V:e.V}}}));a.O.count.value+=1;a.O.ca=!1;return a},
["delete"](){this.O.R||Na(this);if(this.O.ca&&!this.O.da)throw new O("Object already scheduled for deletion");Pa(this);var a=this.O;--a.count.value;0===a.count.value&&(a.T?a.V.Y(a.T):a.S.P.Y(a.R));this.O.da||(this.O.T=void 0,this.O.R=void 0)},isDeleted:function(){return!this.O.R},deleteLater:function(){this.O.R||Na(this);if(this.O.ca&&!this.O.da)throw new O("Object already scheduled for deletion");Va.push(this);this.O.ca=!0;return this}});
Object.assign(fb.prototype,{ra(a){this.ma&&(a=this.ma(a));return a},ka(a){this.Y?.(a)},X:8,readValueFromPointer:H,fromWireType:function(a){function b(){return this.ga?Ua(this.P.aa,{S:this.xa,R:c,V:this,T:a}):Ua(this.P.aa,{S:this,R:a})}var c=this.ra(a);if(!c)return this.ka(a),null;var d=Ta(this.P,c);if(void 0!==d){if(0===d.O.count.value)return d.O.R=c,d.O.T=a,d.clone();d=d.clone();this.ka(a);return d}d=this.P.qa(c);d=Ra[d];if(!d)return b.call(this);d=this.fa?d.na:d.pointerType;var e=Qa(c,this.P,d.P);
return null===e?b.call(this):this.ga?Ua(d.P.aa,{S:d,R:e,V:this,T:a}):Ua(d.P.aa,{S:d,R:e})}});mb=m.UnboundTypeError=((a,b)=>{var c=Q(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
U.push(0,1,void 0,1,null,1,!0,1,!1,1);m.count_emval_handles=()=>U.length/2-5-wb.length;
var $b={k:(a,b,c)=>{var d=new Da(a);D[d.R+16>>2]=0;D[d.R+4>>2]=b;D[d.R+8>>2]=c;Ea=a;Ga++;throw Ea;},v:()=>ua(""),A:a=>{var b=Ha[a];delete Ha[a];var c=b.ia,d=b.Y,e=b.la,g=e.map(h=>h.ua).concat(e.map(h=>h.Ba));M([a],g,h=>{var f={};e.forEach((l,k)=>{var n=h[k],q=l.sa,r=l.ta,v=h[k+e.length],t=l.Aa,z=l.Ca;f[l.pa]={read:F=>n.fromWireType(q(r,F)),write:(F,W)=>{var y=[];t(z,F,v.toWireType(y,W));Ia(y)}}});return[{name:b.name,fromWireType:l=>{var k={},n;for(n in f)k[n]=f[n].read(l);d(l);return k},toWireType:(l,
k)=>{for(var n in f)if(!(n in k))throw new TypeError(`Missing field: "${n}"`);var q=c();for(n in f)f[n].write(q,k[n]);null!==l&&l.push(d,q);return q},X:8,readValueFromPointer:H,W:d}]})},q:()=>{},B:(a,b,c,d)=>{b=N(b);L(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},X:8,readValueFromPointer:function(e){return this.fromWireType(A[e])},W:null})},t:(a,b,c,d,e,g,h,f,l,k,n,q,r)=>{n=N(n);g=S(e,g);f&&=S(h,f);k&&=S(l,k);r=S(q,r);var v=Za(n);Ya(v,function(){qb(`Cannot construct ${n} due to unbound types`,
[d])});M([a,b,c],d?[d]:[],t=>{t=t[0];if(d){var z=t.P;var F=z.aa}else F=Wa.prototype;t=Q(n,function(...Fa){if(Object.getPrototypeOf(this)!==W)throw new O("Use 'new' to construct "+n);if(void 0===y.$)throw new O(n+" has no accessible constructor");var nb=y.$[Fa.length];if(void 0===nb)throw new O(`Tried to invoke ctor of ${n} with invalid number of parameters (${Fa.length}) - expected (${Object.keys(y.$).toString()}) parameters instead!`);return nb.apply(this,Fa)});var W=Object.create(F,{constructor:{value:t}});
t.prototype=W;var y=new $a(n,t,W,r,z,g,f,k);if(y.U){var X;(X=y.U).ja??(X.ja=[]);y.U.ja.push(y)}z=new fb(n,y,!0,!1,!1);X=new fb(n+"*",y,!1,!1,!1);F=new fb(n+" const*",y,!1,!0,!1);Ra[a]={pointerType:X,na:F};gb(v,t);return[z,X,F]})},p:(a,b,c,d,e,g)=>{var h=rb(b,c);e=S(d,e);M([],[a],f=>{f=f[0];var l=`constructor ${f.name}`;void 0===f.P.$&&(f.P.$=[]);if(void 0!==f.P.$[b-1])throw new O(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
f.P.$[b-1]=()=>{qb(`Cannot construct ${f.name} due to unbound types`,h)};M([],h,k=>{k.splice(1,0,null);f.P.$[b-1]=ub(l,k,null,e,g);return[]});return[]})},j:(a,b,c,d,e,g,h,f,l)=>{var k=rb(c,d);b=N(b);b=vb(b);g=S(e,g);M([],[a],n=>{function q(){qb(`Cannot call ${r} due to unbound types`,k)}n=n[0];var r=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);f&&n.P.ya.push(b);var v=n.P.aa,t=v[b];void 0===t||void 0===t.Z&&t.className!==n.name&&t.ba===c-2?(q.ba=c-2,q.className=n.name,v[b]=q):(Xa(v,
b,r),v[b].Z[c-2]=q);M([],k,z=>{z=ub(r,z,n,g,h,l);void 0===v[b].Z?(z.ba=c-2,v[b]=z):v[b].Z[c-2]=z;return[]});return[]})},y:a=>L(a,yb),i:(a,b,c)=>{b=N(b);L(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,X:8,readValueFromPointer:zb(b,c),W:null})},c:(a,b,c,d,e)=>{b=N(b);-1===e&&(e=4294967295);e=f=>f;if(0===d){var g=32-8*c;e=f=>f<<g>>>g}var h=b.includes("unsigned")?function(f,l){return l>>>0}:function(f,l){return l};L(a,{name:b,fromWireType:e,toWireType:h,X:8,readValueFromPointer:Ab(b,c,0!==d),W:null})},
a:(a,b,c)=>{function d(g){return new e(la.buffer,D[g+4>>2],D[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);L(a,{name:c,fromWireType:d,X:8,readValueFromPointer:d},{va:!0})},z:(a,b)=>{b=N(b);L(a,{name:b,fromWireType:function(c){for(var d=D[c>>2],e=c+4,g,h=e,f=0;f<=d;++f){var l=e+f;if(f==d||0==A[l])h=h?Cb(h,l-h):"",void 0===g?g=h:(g+=String.fromCharCode(0),g+=h),h=l+1}T(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&
(d=new Uint8Array(d));var e,g="string"==typeof d;if(!(g||d instanceof Uint8Array||d instanceof Uint8ClampedArray||d instanceof Int8Array))throw new O("Cannot pass non-string to std::string");var h;if(g)for(e=h=0;e<d.length;++e){var f=d.charCodeAt(e);127>=f?h++:2047>=f?h+=2:55296<=f&&57343>=f?(h+=4,++e):h+=3}else h=d.length;e=h;h=Yb(4+e+1);f=h+4;D[h>>2]=e;if(g){if(g=f,f=e+1,e=A,0<f){f=g+f-1;for(var l=0;l<d.length;++l){var k=d.charCodeAt(l);if(55296<=k&&57343>=k){var n=d.charCodeAt(++l);k=65536+((k&
1023)<<10)|n&1023}if(127>=k){if(g>=f)break;e[g++]=k}else{if(2047>=k){if(g+1>=f)break;e[g++]=192|k>>6}else{if(65535>=k){if(g+2>=f)break;e[g++]=224|k>>12}else{if(g+3>=f)break;e[g++]=240|k>>18;e[g++]=128|k>>12&63}e[g++]=128|k>>6&63}e[g++]=128|k&63}}e[g]=0}}else if(g)for(g=0;g<e;++g){l=d.charCodeAt(g);if(255<l)throw T(f),new O("String has UTF-16 code units that do not fit in 8 bits");A[f+g]=l}else for(g=0;g<e;++g)A[f+g]=d[g];null!==c&&c.push(T,h);return h},X:8,readValueFromPointer:H,W(c){T(c)}})},e:(a,
b,c)=>{c=N(c);if(2===b){var d=Eb;var e=Fb;var g=Gb;var h=f=>ma[f>>1]}else 4===b&&(d=Hb,e=Ib,g=Jb,h=f=>D[f>>2]);L(a,{name:c,fromWireType:f=>{for(var l=D[f>>2],k,n=f+4,q=0;q<=l;++q){var r=f+4+q*b;if(q==l||0==h(r))n=d(n,r-n),void 0===k?k=n:(k+=String.fromCharCode(0),k+=n),n=r+b}T(f);return k},toWireType:(f,l)=>{if("string"!=typeof l)throw new O(`Cannot pass non-string to C++ string type ${c}`);var k=g(l),n=Yb(4+k+b);D[n>>2]=k/b;e(l,n+4,k+b);null!==f&&f.push(T,n);return n},X:8,readValueFromPointer:H,
W(f){T(f)}})},G:(a,b,c,d,e,g)=>{Ha[a]={name:N(b),ia:S(c,d),Y:S(e,g),la:[]}},d:(a,b,c,d,e,g,h,f,l,k)=>{Ha[a].la.push({pa:N(b),ua:c,sa:S(d,e),ta:g,Ba:h,Aa:S(f,l),Ca:k})},C:(a,b)=>{b=N(b);L(a,{wa:!0,name:b,X:0,fromWireType:()=>{},toWireType:()=>{}})},x:(a,b,c)=>A.copyWithin(a,b,b+c),s:()=>{Ca=!1;Kb=0},F:(a,b,c)=>{a=V(a);b=Lb(b,"emval::as");return Mb(b,c,a)},n:(a,b,c,d)=>{a=Nb[a];b=V(b);return a(null,b,c,d)},D:(a,b,c,d,e)=>{a=Nb[a];b=V(b);c=Pb(c);return a(b,b[c],d,e)},b:xb,o:a=>{if(0===a)return R(Qb());
a=Pb(a);return R(Qb()[a])},g:(a,b,c)=>{b=Sb(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",g=0,h=[];0===c&&h.push("obj");for(var f=["retType"],l=[d],k=0;k<a;++k)h.push("arg"+k),f.push("argType"+k),l.push(b[k]),e+=`  var arg${k} = argType${k}.readValueFromPointer(args${g?"+"+g:""});\n`,g+=b[k].X;e+=`  var rv = ${1===c?"new func":"func.call"}(${h.join(", ")});\n`;d.wa||(f.push("emval_returnValue"),l.push(Mb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");
f.push(e+"};\n");a=tb(f)(...l);c=`methodCaller<(${b.map(n=>n.name).join(", ")}) => ${d.name}>`;return Rb(Q(c,a))},m:(a,b)=>{a=V(a);b=V(b);return R(a[b])},h:a=>{9<a&&(U[a+1]+=1)},l:a=>R(Pb(a)),f:a=>{var b=V(a);Ia(b);xb(a)},E:(a,b)=>{a=Lb(a,"_emval_take_value");a=a.readValueFromPointer(b);return R(a)},u:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];Vb(()=>Zb(a,performance.now()))},b);Y[a]={id:c,Ea:b};return 0},w:a=>{var b=A.length;a>>>=0;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ia.buffer.byteLength+65535)/65536|0;try{ia.grow(d);pa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},r:Ub},Z;
(async function(){function a(d){Z=d.exports;ia=Z.H;pa();ib=Z.M;ra.unshift(Z.I);E--;m.monitorRunDependencies?.(E);0==E&&G&&(d=G,G=null,d());return Z}E++;m.monitorRunDependencies?.(E);var b={a:$b};if(m.instantiateWasm)try{return m.instantiateWasm(b,a)}catch(d){w(`Module.instantiateWasm callback failed with error: ${d}`),p(d)}wa??=m.locateFile?va("init.wasm")?"init.wasm":m.locateFile?m.locateFile("init.wasm",u):u+"init.wasm":(new URL("init.wasm",import.meta.url)).href;try{var c=await za(b);
a(c.instance);return c}catch(d){p(d)}})();var ob=a=>(ob=Z.J)(a),Zb=(a,b)=>(Zb=Z.K)(a,b),Yb=a=>(Yb=Z.L)(a),T=a=>(T=Z.N)(a),ac;G=function bc(){ac||cc();ac||(G=bc)};
function cc(){function a(){if(!ac&&(ac=!0,m.calledRun=!0,!ja)){Ba(ra);aa(m);m.onRuntimeInitialized?.();if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var b=m.postRun.shift();sa.unshift(b)}Ba(sa)}}if(!(0<E)){if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)ta();Ba(qa);0<E||(m.setStatus?(m.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>m.setStatus(""),1);a()},1)):a())}}
if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();cc();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default Module;
