
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var g=moduleArg,aa,q,ba=new Promise((a,b)=>{aa=a;q=b}),ca="object"==typeof window,da="undefined"!=typeof WorkerGlobalScope,ea=Object.assign({},g),r="",fa,ha;
if(ca||da)da?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),_scriptName&&(r=_scriptName),r.startsWith("blob:")?r="":r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1),da&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var t=g.printErr||console.error.bind(console);Object.assign(g,ea);ea=null;var v=g.wasmBinary,x,y=!1,ia,ja,A,B,C,D,E,ka,la;function ma(){var a=x.buffer;g.HEAP8=ja=new Int8Array(a);g.HEAP16=B=new Int16Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=C=new Uint16Array(a);g.HEAP32=D=new Int32Array(a);g.HEAPU32=E=new Uint32Array(a);g.HEAPF32=ka=new Float32Array(a);g.HEAPF64=la=new Float64Array(a)}var na=[],oa=[],pa=[];function ra(){var a=g.preRun.shift();na.unshift(a)}var G=0,H=null;
function sa(a){g.onAbort?.(a);a="Aborted("+a+")";t(a);y=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");q(a);throw a;}var ta=a=>a.startsWith("data:application/octet-stream;base64,"),ua;async function va(a){if(!v)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==ua&&v)a=new Uint8Array(v);else if(ha)a=ha(a);else throw"both async and sync fetching of the wasm failed";return a}
async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}async function xa(a){var b=ua;if(!v&&"function"==typeof WebAssembly.instantiateStreaming&&!ta(b)&&"function"==typeof fetch)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return wa(b,a)}
class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var za=a=>{for(;0<a.length;)a.shift()(g)},Aa=g.noExitRuntime||!0;class Ba{constructor(a){this.O=a-24}}
var Ca=0,Da=0,Ea,I=a=>{for(var b="";A[a];)b+=Ea[A[a++]];return b},J={},K={},L={},M,Fa=a=>{throw new M(a);},Ga,Ha=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new Ga("Mismatched type converter count");for(var k=0;k<d.length;++k)N(d[k],h[k])}var d=[];d.forEach(h=>L[h]=a);var e=Array(a.length),f=[],l=0;a.forEach((h,k)=>{K.hasOwnProperty(h)?e[k]=K[h]:(f.push(h),J.hasOwnProperty(h)||(J[h]=[]),J[h].push(()=>{e[k]=K[h];++l;l===f.length&&c(e)}))});0===f.length&&c(e)};
function Ia(a,b,c={}){var d=b.name;if(!a)throw new M(`type "${d}" must have a positive integer typeid pointer`);if(K.hasOwnProperty(a)){if(c.R)return;throw new M(`Cannot register type '${d}' twice`);}K[a]=b;delete L[a];J.hasOwnProperty(a)&&(b=J[a],delete J[a],b.forEach(e=>e()))}function N(a,b,c={}){return Ia(a,b,c)}
var Ja=[],Q=[],Ka=a=>{9<a&&0===--Q[a+1]&&(Q[a]=void 0,Ja.push(a))},R=a=>{if(!a)throw new M("Cannot use deleted val. handle = "+a);return Q[a]},S=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ja.pop()||Q.length;Q[b]=a;Q[b+1]=1;return b}};function La(a){return this.fromWireType(E[a>>2])}
var Ma={name:"emscripten::val",fromWireType:a=>{var b=R(a);Ka(a);return b},toWireType:(a,b)=>S(b),N:8,readValueFromPointer:La,M:null},Na=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ka[c>>2])};case 8:return function(c){return this.fromWireType(la[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},T=(a,b)=>Object.defineProperty(b,"name",{value:a}),Oa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Pa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].M)return!0;return!1}function Qa(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=T(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
for(var Ra=(a,b)=>{if(void 0===g[a].L){var c=g[a];g[a]=function(...d){if(!g[a].L.hasOwnProperty(d.length))throw new M(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${g[a].L})!`);return g[a].L[d.length].apply(this,d)};g[a].L=[];g[a].L[c.P]=c}},Sa=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].L&&void 0!==g[a].L[c])throw new M(`Cannot register public name '${a}' twice`);Ra(a,a);if(g[a].L.hasOwnProperty(c))throw new M(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
g[a].L[c]=b}else g[a]=b,g[a].P=c},Ta=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},U=[],Ua,Ya=a=>{var b=U[a];b||(a>=U.length&&(U.length=a+1),U[a]=b=Ua.get(a));return b},Za=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,g["dynCall_"+a])(b,...c)):b=Ya(b)(...c);return b},$a=(a,b)=>(...c)=>Za(a,b,c),ab=(a,b)=>{a=I(a);var c=a.includes("j")?$a(a,b):Ya(b);if("function"!=typeof c)throw new M(`unknown function pointer with signature ${a}: ${b}`);return c},bb,db=a=>{a=cb(a);var b=
I(a);V(a);return b},eb=(a,b)=>{function c(f){e[f]||K[f]||(L[f]?L[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new bb(`${a}: `+d.map(db).join([", "]));},fb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},gb=(a,b,c)=>{switch(b){case 1:return c?d=>ja[d]:d=>A[d];case 2:return c?d=>B[d>>1]:d=>C[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},hb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,
ib=(a=0,b=NaN)=>{var c=A,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&hb)return hb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var f=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=c[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},jb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):
void 0,kb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&C[c];)++c;c<<=1;if(32<c-a&&jb)return jb.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},lb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d},mb=a=>2*a.length,nb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=D[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ob=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},qb=0,rb=(a,b)=>{var c=K[a];if(void 0===c)throw a=`${b} has unknown type ${db(a)}`,new M(a);return c},sb=(a,
b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(E[b>>2]=S(d));return a},W=[],tb={},ub=a=>{var b=tb[a];return void 0===b?I(a):b},vb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),wb=a=>{var b=W.length;W.push(a);return b},xb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=rb(E[b+4*d>>2],"parameter "+d);return c},X={},yb=a=>{if(!(a instanceof ya||"unwind"==a))throw a;},zb=a=>{ia=a;Aa||0<qb||(g.onExit?.(a),y=!0);throw new ya(a);},Ab=a=>{if(!y)try{if(a(),!(Aa||0<qb))try{ia=a=ia,zb(a)}catch(b){yb(b)}}catch(b){yb(b)}},
Bb=Array(256),Y=0;256>Y;++Y)Bb[Y]=String.fromCharCode(Y);Ea=Bb;M=g.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Ga=g.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Q.push(0,1,void 0,1,null,1,!0,1,!1,1);g.count_emval_handles=()=>Q.length/2-5-Ja.length;
bb=g.UnboundTypeError=((a,b)=>{var c=T(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Eb={h:(a,b,c)=>{var d=new Ba(a);E[d.O+16>>2]=0;E[d.O+4>>2]=b;E[d.O+8>>2]=c;Ca=a;Da++;throw Ca;},u:()=>sa(""),q:()=>{},z:(a,b,c,d)=>{b=I(b);N(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},N:8,readValueFromPointer:function(e){return this.fromWireType(A[e])},M:null})},x:a=>N(a,Ma),k:(a,b,c)=>{b=I(b);N(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,N:8,readValueFromPointer:Na(b,c),M:null})},l:(a,b,c,d,e,f,l)=>{var h=Ta(b,c);a=I(a);a=fb(a);e=ab(d,e);Sa(a,function(){eb(`Cannot call ${a} due to unbound types`,
h)},b-1);Ha(h,k=>{var m=a;var p=a;k=[k[0],null].concat(k.slice(1));var z=e,n=k.length;if(2>n)throw new M("argTypes array size mismatch! Must at least get return value and 'this' types!");var F=null!==k[1]&&!1,O=Pa(k),Va="void"!==k[0].name;z=[p,Fa,z,f,Oa,k[0],k[1]];for(var w=0;w<n-2;++w)z.push(k[w+2]);if(!O)for(w=F?1:2;w<k.length;++w)null!==k[w].M&&z.push(k[w].M);O=Pa(k);w=k.length-2;var u=[],P=["fn"];F&&P.push("thisWired");for(n=0;n<w;++n)u.push(`arg${n}`),P.push(`arg${n}Wired`);u=u.join(",");P=P.join(",");
u=`return function (${u}) {\n`;O&&(u+="var destructors = [];\n");var Wa=O?"destructors":"null",qa="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");F&&(u+=`var thisWired = classParam['toWireType'](${Wa}, this);\n`);for(n=0;n<w;++n)u+=`var arg${n}Wired = argType${n}['toWireType'](${Wa}, arg${n});\n`,qa.push(`argType${n}`);u+=(Va||l?"var rv = ":"")+`invoker(${P});\n`;if(O)u+="runDestructors(destructors);\n";else for(n=F?1:2;n<k.length;++n)F=1===n?"thisWired":"arg"+
(n-2)+"Wired",null!==k[n].M&&(u+=`${F}_dtor(${F});\n`,qa.push(`${F}_dtor`));Va&&(u+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [Xa,Gb]=[qa,u+"}\n"];Xa.push(Gb);k=Qa(Xa)(...z);p=T(p,k);k=b-1;if(!g.hasOwnProperty(m))throw new Ga("Replacing nonexistent public symbol");void 0!==g[m].L&&void 0!==k?g[m].L[k]=p:(g[m]=p,g[m].P=k);return[]})},c:(a,b,c,d,e)=>{b=I(b);-1===e&&(e=4294967295);e=h=>h;if(0===d){var f=32-8*c;e=h=>h<<f>>>f}var l=b.includes("unsigned")?function(h,k){return k>>>0}:
function(h,k){return k};N(a,{name:b,fromWireType:e,toWireType:l,N:8,readValueFromPointer:gb(b,c,0!==d),M:null})},a:(a,b,c)=>{function d(f){return new e(ja.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=I(c);N(a,{name:c,fromWireType:d,N:8,readValueFromPointer:d},{R:!0})},y:(a,b)=>{b=I(b);N(a,{name:b,fromWireType:function(c){for(var d=E[c>>2],e=c+4,f,l=e,h=0;h<=d;++h){var k=e+h;if(h==d||0==A[k])l=l?ib(l,k-l):"",void 0===
f?f=l:(f+=String.fromCharCode(0),f+=l),l=k+1}V(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;if(!(f||d instanceof Uint8Array||d instanceof Uint8ClampedArray||d instanceof Int8Array))throw new M("Cannot pass non-string to std::string");var l;if(f)for(e=l=0;e<d.length;++e){var h=d.charCodeAt(e);127>=h?l++:2047>=h?l+=2:55296<=h&&57343>=h?(l+=4,++e):l+=3}else l=d.length;e=l;l=Cb(4+e+1);h=l+4;E[l>>2]=e;if(f){if(f=h,h=e+1,e=A,0<h){h=f+h-
1;for(var k=0;k<d.length;++k){var m=d.charCodeAt(k);if(55296<=m&&57343>=m){var p=d.charCodeAt(++k);m=65536+((m&1023)<<10)|p&1023}if(127>=m){if(f>=h)break;e[f++]=m}else{if(2047>=m){if(f+1>=h)break;e[f++]=192|m>>6}else{if(65535>=m){if(f+2>=h)break;e[f++]=224|m>>12}else{if(f+3>=h)break;e[f++]=240|m>>18;e[f++]=128|m>>12&63}e[f++]=128|m>>6&63}e[f++]=128|m&63}}e[f]=0}}else if(f)for(f=0;f<e;++f){k=d.charCodeAt(f);if(255<k)throw V(h),new M("String has UTF-16 code units that do not fit in 8 bits");A[h+f]=
k}else for(f=0;f<e;++f)A[h+f]=d[f];null!==c&&c.push(V,l);return l},N:8,readValueFromPointer:La,M(c){V(c)}})},f:(a,b,c)=>{c=I(c);if(2===b){var d=kb;var e=lb;var f=mb;var l=h=>C[h>>1]}else 4===b&&(d=nb,e=ob,f=pb,l=h=>E[h>>2]);N(a,{name:c,fromWireType:h=>{for(var k=E[h>>2],m,p=h+4,z=0;z<=k;++z){var n=h+4+z*b;if(z==k||0==l(n))p=d(p,n-p),void 0===m?m=p:(m+=String.fromCharCode(0),m+=p),p=n+b}V(h);return m},toWireType:(h,k)=>{if("string"!=typeof k)throw new M(`Cannot pass non-string to C++ string type ${c}`);
var m=f(k),p=Cb(4+m+b);E[p>>2]=m/b;e(k,p+4,m+b);null!==h&&h.push(V,p);return p},N:8,readValueFromPointer:La,M(h){V(h)}})},A:(a,b)=>{b=I(b);N(a,{S:!0,name:b,N:0,fromWireType:()=>{},toWireType:()=>{}})},w:(a,b,c)=>A.copyWithin(a,b,b+c),s:()=>{Aa=!1;qb=0},o:(a,b,c)=>{a=R(a);b=rb(b,"emval::as");return sb(b,c,a)},p:(a,b,c,d)=>{a=W[a];b=R(b);return a(null,b,c,d)},m:(a,b,c,d,e)=>{a=W[a];b=R(b);c=ub(c);return a(b,b[c],d,e)},b:Ka,D:a=>{if(0===a)return S(vb());a=ub(a);return S(vb()[a])},e:(a,b,c)=>{b=xb(a,
b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,l=[];0===c&&l.push("obj");for(var h=["retType"],k=[d],m=0;m<a;++m)l.push("arg"+m),h.push("argType"+m),k.push(b[m]),e+=`  var arg${m} = argType${m}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[m].N;e+=`  var rv = ${1===c?"new func":"func.call"}(${l.join(", ")});\n`;d.S||(h.push("emval_returnValue"),k.push(sb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");h.push(e+"};\n");a=Qa(h)(...k);c=
`methodCaller<(${b.map(p=>p.name).join(", ")}) => ${d.name}>`;return wb(T(c,a))},j:(a,b)=>{a=R(a);b=R(b);return S(a[b])},g:a=>{9<a&&(Q[a+1]+=1)},B:()=>S([]),C:a=>{a=R(a);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return S(b)},i:a=>S(ub(a)),d:a=>{var b=R(a);Oa(b);Ka(a)},n:(a,b)=>{a=rb(a,"_emval_take_value");a=a.readValueFromPointer(b);return S(a)},t:(a,b)=>{X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var c=setTimeout(()=>{delete X[a];Ab(()=>Db(a,performance.now()))},b);X[a]=
{id:c,T:b};return 0},v:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-x.buffer.byteLength+65535)/65536|0;try{x.grow(d);ma();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},r:zb},Z;
(async function(){function a(d){Z=d.exports;x=Z.E;ma();Ua=Z.J;oa.unshift(Z.F);G--;g.monitorRunDependencies?.(G);0==G&&H&&(d=H,H=null,d());return Z}G++;g.monitorRunDependencies?.(G);var b={a:Eb};if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(d){t(`Module.instantiateWasm callback failed with error: ${d}`),q(d)}ua??=g.locateFile?ta("color.wasm")?"color.wasm":g.locateFile?g.locateFile("color.wasm",r):r+"color.wasm":(new URL("color.wasm",import.meta.url)).href;try{var c=await xa(b);
a(c.instance);return c}catch(d){q(d)}})();var cb=a=>(cb=Z.G)(a),Db=(a,b)=>(Db=Z.H)(a,b),Cb=a=>(Cb=Z.I)(a),V=a=>(V=Z.K)(a),Fb;H=function Hb(){Fb||Ib();Fb||(H=Hb)};
function Ib(){function a(){if(!Fb&&(Fb=!0,g.calledRun=!0,!y)){za(oa);aa(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();pa.unshift(b)}za(pa)}}if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ra();za(na);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a())}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Ib();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default Module;
